(()=>{
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],R=(a,b)=>Math.floor(Math.random()*(b-a+1))+a,C=(v,a,b)=>Math.max(a,Math.min(b,v));
const PARTY=[['關羽',9999,94,80,70,58,14],['張苞',9999,88,76,66,44,10],['周瑜',9558,76,68,82,96,40],['趙雲',9600,91,77,89,64,16],['姜維',9800,86,72,80,88,30]].map(([name,max,atk,def,agi,int,sp])=>({name,max,hp:max,atk,def,agi,int,sp,maxSp:sp}));
const EB={'司馬懿':[28000,92,85,78,98,50],'司馬炎':[26000,84,78,70,88,34],'鄧艾':[24000,90,80,75,72,18],'鍾會':[24000,86,76,82,86,30],'徐晃':[24000,93,82,68,54,8],'曹仁':[22000,88,84,66,58,10],'張郃':[22800,90,76,80,62,12],'夏侯惇':[25000,95,83,72,58,12],'郭淮':[21500,81,74,70,80,22]};
const TEAMS=[['司馬懿','司馬炎','鄧艾','鍾會','徐晃'],['曹仁','張郃','夏侯惇','郭淮','徐晃'],['司馬懿','張郃','鄧艾','鍾會','郭淮']];
const SK=[['落雷計',8,'dmg',1.72],['火焰計',5,'dmg',1.28],['聖雨',6,'heal',1],['金仙計',7,'weak',1]];
const MAP=['WWWWWWWWWWWWWWWWWWWWWWWW','W......F....WW.....F...W','W..TTT..R...WW..TTT....W','W..T.T..R........TT....W','W......RRRRRR........F.W','W.F....R..VR....F......W','W......R...R.........T.W','W..TT..R...RRRR....TT..W','W......R......R..F.....W','W...F..R..C...R........W','W......RRRRRRRR...B....W','W..............R.......W','W..TT......F...R.......W','WWWWWWWWWWWWWWWWWWWWWWWW'];
const PLACE={C:'新野城',V:'隆中村',B:'博望坡'},QUEST=['前往隆中村尋訪孔明','返回新野城整備兵馬','前往博望坡迎擊曹軍','擊敗夏侯惇，完成首戰'];
const PAL={
'關羽':['#4d8c64','#c53d4b','#e5b84d','blade'],'張苞':['#c77b2e','#c53d4b','#232631','spear'],'周瑜':['#6d53a8','#edf3ff','#e5b84d','fan'],'趙雲':['#5678c9','#cad6ef','#edf3ff','spear'],'姜維':['#65b5b0','#6b4730','#e5b84d','spear'],
'司馬懿':['#6d53a8','#232631','#cad6ef','staff'],'司馬炎':['#c53d4b','#6d53a8','#cad6ef','sword'],'鄧艾':['#4d8c64','#6b4730','#cad6ef','axe'],'鍾會':['#c77b2e','#c53d4b','#cad6ef','sword'],'徐晃':['#6b4730','#e5b84d','#cad6ef','axe'],'曹仁':['#5678c9','#232631','#cad6ef','shield'],'張郃':['#6d53a8','#c53d4b','#cad6ef','spear'],'夏侯惇':['#c53d4b','#232631','#cad6ef','sword'],'郭淮':['#4d8c64','#6d53a8','#cad6ef','staff']};
let S=null,B=null;
const A={ctx:null,on:true,t:null,n:0};
function ac(){if(!A.on)return null;if(!A.ctx){let X=window.AudioContext||window.webkitAudioContext;if(!X)return null;A.ctx=new X}if(A.ctx.state==='suspended')A.ctx.resume();return A.ctx}
function tone(f,d=.08,type='square',v=.025){let x=ac();if(!x)return;let o=x.createOscillator(),g=x.createGain(),t=x.currentTime;o.type=type;o.frequency.value=f;g.gain.value=v;o.connect(g);g.connect(x.destination);g.gain.exponentialRampToValueAtTime(.0001,t+d);o.start(t);o.stop(t+d)}
function fx(k){if(!A.on)return;let m={move:[540],sel:[660,880],hit:[180,120],cast:[620,780,980],heal:[480,660,900],win:[660,880,1040,1320],lose:[420,300,220]}[k]||[];m.forEach((f,i)=>setTimeout(()=>tone(f,k==='win'?.14:.1,k==='lose'?'triangle':'square',.02),i*55))}
function bgm(){clearInterval(A.t);if(!A.on)return;ac();let m=[523,659,784,659,587,659,698,659,523,659,880,784,698,659,587,523],b=[196,196,220,220,175,175,196,196];A.n=0;A.t=setInterval(()=>{tone(m[A.n%m.length],.1,'square',.011);tone(b[A.n%b.length],.16,'triangle',.008);A.n++},230)}
function audioToggle(){A.on=!A.on;if(A.on){bgm();fx('sel');toast('聲音已開啟')}else{clearInterval(A.t);toast('聲音已關閉')}audioUI()}
function audioUI(){if($('#audioState'))$('#audioState').textContent=`聲音 ${A.on?'開':'關'}`;if($('#soundToggle'))$('#soundToggle').textContent=`音效：${A.on?'開啟':'關閉'}`}
function state(){return{x:3,y:9,gold:300,food:3,form:'鶴翼',party:structuredClone(PARTY),steps:0,battles:0,quest:0,story:{v:false,c:false,b:false}}}
function show(id){$$('.screen').forEach(e=>e.classList.remove('on'));$(id).classList.add('on')}
function toast(t){let e=$('#toast');e.textContent=t;e.classList.add('on');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('on'),1100)}
function wm(t){$('#wmsg').textContent=t} function bm(t){$('#bmsg').textContent=t}
function save(){localStorage.setItem('sanguo-kongming-save-v4',JSON.stringify(S));toast('進度已保存')}
function load(){let r=localStorage.getItem('sanguo-kongming-save-v4');if(!r){alert('目前沒有 V4 存檔。請先開始新遊戲。');return}S=JSON.parse(r);show('#world');hud();map();bgm();wm('已讀取 V4 進度。')}
function hud(){let t=MAP[S.y][S.x];$('#loc').textContent=PLACE[t]||'荊州北境';$('#money').textContent=`金 ${S.gold}`;$('#foodPill').textContent=`軍糧 ${S.food}`;$('#team').textContent=`隊伍 ${S.party.filter(x=>x.hp>0).length}/5　陣 ${S.form}`;$('#questText').textContent=`目標：${QUEST[S.quest]}`;audioUI()}
function p(c,x,y,w,h,col){c.fillStyle=col;c.fillRect(x,y,w,h)}
function sprite(name){let cv=document.createElement('canvas'),c=cv.getContext('2d');cv.width=cv.height=32;let [body,trim,metal,gear]=PAL[name]||['#5678c9','#232631','#cad6ef','sword'];p(c,8,28,16,2,'#0005');p(c,11,4,10,3,trim);p(c,12,7,8,6,'#f0c79b');p(c,11,7,10,2,trim);p(c,10,13,12,11,body);p(c,8,14,3,7,'#f0c79b');p(c,13,24,4,5,'#60422f');p(c,19,24,4,5,'#60422f');p(c,14,9,1,1,'#111');p(c,18,9,1,1,'#111');p(c,13,15,6,3,trim);
if(gear==='spear'){p(c,24,5,2,21,metal);p(c,23,4,4,3,'#f5f7ff')}if(gear==='sword'){p(c,24,10,3,14,metal);p(c,23,9,5,3,'#ffd56a')}if(gear==='axe'){p(c,24,8,2,17,'#6b4730');p(c,22,6,7,5,metal)}if(gear==='staff'){p(c,25,7,2,19,'#8a5a38');p(c,23,5,6,5,trim)}if(gear==='fan'){p(c,24,8,5,8,metal);p(c,25,7,3,2,'#fff')}if(gear==='blade'){p(c,24,6,2,20,'#7b5a31');p(c,22,4,7,4,metal);p(c,27,3,2,5,metal)}if(gear==='shield'){p(c,23,11,7,11,metal);p(c,25,13,3,6,trim)}
if(name==='關羽')p(c,14,13,5,11,'#632e20');if(name==='夏侯惇')p(c,13,9,2,2,'#b82020');return cv.toDataURL()}
function portrait(name){let cv=document.createElement('canvas'),c=cv.getContext('2d');cv.width=cv.height=40;let q=PAL[name]||['#5678c9','#232631'];p(c,0,0,40,40,'#f4f4e8');p(c,9,7,22,20,'#f0c79b');p(c,7,4,26,7,q[1]);p(c,6,10,4,16,q[1]);p(c,30,10,4,16,q[1]);p(c,14,15,3,2,'#111');p(c,23,15,3,2,'#111');p(c,18,22,5,2,'#111');p(c,10,28,20,10,q[0]);return cv}
function hero(c,x,y){p(c,x+2,y+14,12,2,'#0004');p(c,x+5,y+1,7,3,'#eef5ff');p(c,x+6,y+4,6,4,'#f0c79b');p(c,x+5,y+7,8,2,'#cad6ef');p(c,x+5,y+9,8,7,'#5678c9');p(c,x+13,y+8,2,7,'#eef5ff')}
function map(){let cv=$('#map'),c=cv.getContext('2d'),tw=16,cols=12,rows=10,cx=C(S.x-6,0,MAP[0].length-cols),cy=C(S.y-5,0,MAP.length-rows),sx=cv.width/(cols*tw),sy=cv.height/(rows*tw);c.clearRect(0,0,cv.width,cv.height);c.save();c.scale(sx,sy);for(let y=0;y<rows;y++)for(let x=0;x<cols;x++){let t=MAP[cy+y][cx+x],X=x*tw,Y=y*tw;if(t==='W'){p(c,X,Y,tw,tw,'#21659a');p(c,X,Y+2,tw,2,'#63b9ea')}else{p(c,X,Y,tw,tw,'#6ca451');if(t==='R'){p(c,X,Y,tw,tw,'#b39469');p(c,X,Y+5,tw,3,'#ccb083')}if(t==='F'||t==='T'){p(c,X+3,Y+4,10,10,t==='F'?'#2a6030':'#356d39');p(c,X+7,Y+10,2,5,'#68462d')}if('CVB'.includes(t)){p(c,X+2,Y+4,12,10,t==='C'?'#b65b4d':t==='V'?'#d4b46c':'#8c493c');p(c,X+6,Y+9,4,5,'#252525')}}}hero(c,(S.x-cx)*tw,(S.y-cy)*tw-2);c.restore()}
function heal(){S.party.forEach(x=>{x.hp=x.max;x.sp=x.maxSp});hud()}
function inspect(){let t=MAP[S.y][S.x];if(t==='V'){S.story.v=true;S.quest=Math.max(S.quest,1);wm('隆中村民：「先生已知主公來意，請先回新野整備。」');hud();fx('sel');return}if(t==='C'){heal();if(S.story.v&&!S.story.c){S.story.c=true;S.quest=2;wm('新野補給完成。下一步前往博望坡。')}else wm('新野城休整完成。');hud();fx('heal');return}if(t==='B'){if(S.story.c&&!S.story.b){wm('夏侯惇率曹軍精銳殺到！');setTimeout(()=>battle(true),300)}else wm('博望坡暫無戰事。');return}wm('孔明觀察附近地形，未發現特殊事件。')}
function move(dx,dy){let x=S.x+dx,y=S.y+dy;if(!MAP[y]||!MAP[y][x]||MAP[y][x]==='W'){wm('前方無法通行。');return}S.x=x;S.y=y;S.steps++;map();hud();fx('move');let t=MAP[y][x];if(t==='C')wm('抵達新野城，按 A 休整。');else if(t==='V')wm('抵達隆中村，按 A 交談。');else if(t==='B')wm('抵達博望坡，按 A 迎戰。');else if(S.story.c&&!S.story.b&&Math.random()<.15)battle(false)}
function enemy(n){let [max,atk,def,agi,int,sp]=EB[n];return{name:n,max,hp:max,atk,def,agi,int,sp,maxSp:sp}}
function battle(boss=false){let names=boss?['司馬懿','司馬炎','鄧艾','鍾會','夏侯惇']:TEAMS[R(0,TEAMS.length-1)];B={allies:S.party,enemies:names.map(enemy),actor:0,sel:null,round:1,guard:new Set(),boss};show('#battle');render();bm(boss?'曹軍主力壓境！':'敵軍逼近！');fx('sel')}
function row(u,i,e){return `<div class="unitRow ${e?'enemyRow':''} ${u.hp<=0?'dead':''}" data-side="${e?'enemy':'ally'}" data-i="${i}">${e?`<div class="nameBlock"><div class="uName">${u.name}</div><div class="uHp">${u.hp}</div><div class="hpBar"><div class="enemyFill" style="width:${C(u.hp/u.max*100,0,100)}%"></div></div></div>`:''}<div class="spritePanel"><div class="spriteFrame"><img class="sprite" src="${sprite(u.name)}"></div></div>${e?'':`<div class="nameBlock"><div class="uName">${u.name}</div><div class="uHp">${u.hp}</div><div class="hpBar"><div class="allyFill" style="width:${C(u.hp/u.max*100,0,100)}%"></div></div></div>`}</div>`}
function render(){$('#allyList').innerHTML=B.allies.map((x,i)=>row(x,i,0)).join('');$('#enemyList').innerHTML=B.enemies.map((x,i)=>row(x,i,1)).join('');$('#battleInfo').innerHTML=`第 ${B.round} 回合<br>${S.form}陣`;let a=B.allies[B.actor]||B.allies.find(x=>x.hp>0),c=$('#portrait').getContext('2d');c.clearRect(0,0,80,80);c.imageSmoothingEnabled=false;c.drawImage(portrait(a.name),0,0,80,80);$('#stats').innerHTML=`<span class="focus"><b>${a.name}</b></span><br>兵力 <span class="green">${a.hp}/${a.max}</span><br>策略 <span class="blue">${a.sp}/${a.maxSp}</span><br>武 ${a.atk}　防 ${a.def}<br>智 ${a.int}　速 ${a.agi}<br>陣型 ${S.form}`;if(B.sel)targets()}
function targets(){$$('.unitRow').forEach(el=>{el.classList.remove('target');el.onclick=null;if(el.dataset.side===B.sel.side){let i=+el.dataset.i,u=B.sel.side==='enemy'?B.enemies[i]:B.allies[i];if(u.hp>0){el.classList.add('target');el.onclick=()=>{let f=B.sel.cb;B.sel=null;f(i)}}}})}
function choose(side,cb){B.sel={side,cb};render();bm(side==='enemy'?'請點選敵軍目標。':'請點選我軍目標。')}
function dmg(a,t,m=1,magic=false){let base=(magic?a.int*11-t.int*3:a.atk*9-t.def*4)*m*(.55+.45*a.hp/a.max);if(S.form==='鋒矢'&&!magic)base*=1.14;let d=Math.max(120,Math.floor(base*R(88,115)/100));if(B.guard.has(t))d=Math.floor(d*.55);if(S.form==='魚鱗'&&B.allies.includes(t))d=Math.floor(d*.88);t.hp=Math.max(0,t.hp-d);return d}
function float(side,i,d){let e=$(`.unitRow[data-side="${side}"][data-i="${i}"]`);if(!e)return;let f=document.createElement('div');f.className='floatDmg';f.textContent='-'+d;e.appendChild(f);setTimeout(()=>f.remove(),700)}
function next(){render();if(B.enemies.every(x=>x.hp<=0))return end(true);let n=B.actor+1;while(n<B.allies.length&&B.allies[n].hp<=0)n++;if(n<B.allies.length){B.actor=n;setTimeout(()=>{render();bm(`${B.allies[n].name} 行動。`)},350)}else setTimeout(enemyTurn,500)}
function enemyTurn(){B.guard.clear();let es=B.enemies.map((x,i)=>[x,i]).filter(x=>x[0].hp>0),i=0;let step=()=>{if(i>=es.length){if(B.allies.every(x=>x.hp<=0))return end(false);B.actor=B.allies.findIndex(x=>x.hp>0);B.round++;render();bm(`第 ${B.round} 回合。${B.allies[B.actor].name} 行動。`);return}let [e]=es[i++],as=B.allies.map((x,j)=>[x,j]).filter(x=>x[0].hp>0),[t,ti]=as[R(0,as.length-1)],d;if(e.int>=80&&e.sp>=6&&Math.random()<.4){e.sp-=6;d=dmg(e,t,1.15,1);bm(`${e.name} 施展計策，${t.name} 損失 ${d}。`);fx('cast')}else{d=dmg(e,t,.9,0);bm(`${e.name} 攻擊 ${t.name}，損失 ${d}。`);fx('hit')}render();float('ally',ti,d);setTimeout(step,390)};step()}
function end(win){if(win){let g=R(260,520)+(B.boss?300:0);S.gold+=g;S.battles++;if(B.boss){S.story.b=true;S.quest=3}save();fx('win');bm(`勝利！獲得 ${g} 金。`);setTimeout(()=>{show('#world');hud();map();wm(B.boss?'博望坡首戰告捷！':'敵軍已退。')},850)}else{fx('lose');bm('我軍潰敗，撤回新野。');setTimeout(()=>{S.x=9;S.y=9;heal();show('#world');map();wm('已在新野重新整軍。')},850)}}
function skills(){let a=B.allies[B.actor],w=$('#skills');w.innerHTML='';SK.forEach(([n,c,t,m])=>{let b=document.createElement('button');b.textContent=`${n} (${c})`;b.disabled=a.sp<c;b.onclick=()=>cast(n,c,t,m);w.appendChild(b)});$('#cmds').style.display='none';w.classList.add('on');bm(`策略值 ${a.sp}。選擇計策。`)}
function cast(n,c,t,m){let a=B.allies[B.actor];if(a.sp<c)return;a.sp-=c;if(t==='dmg')choose('enemy',i=>{let d=dmg(a,B.enemies[i],m,1);bm(`${a.name} 施展${n}，造成 ${d} 損失。`);fx('cast');render();float('enemy',i,d);next()});if(t==='heal')choose('ally',i=>{let u=B.allies[i],h=Math.min(u.max-u.hp,a.int*12+R(300,560));u.hp+=h;bm(`${n}恢復 ${u.name} ${h} 兵力。`);fx('heal');next()});if(t==='weak')choose('enemy',i=>{B.enemies[i].atk=Math.max(30,B.enemies[i].atk-12);bm(`${n}成功，${B.enemies[i].name} 攻擊下降。`);fx('cast');next()})}
function cmd(k){let a=B.allies[B.actor];if(k==='atk')choose('enemy',i=>{let d=dmg(a,B.enemies[i]);bm(`${a.name} 攻擊造成 ${d} 損失。`);fx('hit');render();float('enemy',i,d);next()});if(k==='all')choose('enemy',i=>{let d=0;B.allies.filter(x=>x.hp>0).forEach(x=>d+=dmg(x,B.enemies[i],.55));bm(`全軍總攻！造成 ${d} 損失。`);fx('hit');render();float('enemy',i,d);next()});if(k==='tac')skills();if(k==='form'){let a=['鶴翼','魚鱗','鋒矢','雁行'];S.form=a[(a.indexOf(S.form)+1)%a.length];bm(`變更為${S.form}陣。`);hud();next()}if(k==='item'){if(!S.food)return bm('軍糧不足。');choose('ally',i=>{S.food--;let u=B.allies[i],h=Math.min(u.max-u.hp,R(1300,1800));u.hp+=h;bm(`${u.name} 恢復 ${h}。`);fx('heal');hud();next()})}if(k==='def'){B.guard.add(a);bm(`${a.name} 防禦。`);next()}if(k==='flee'){if(B.boss)return bm('決戰無法撤退！');show('#world');map();hud();wm('成功撤退。')}if(k==='sound')audioToggle()}
function menu(){$('#plist').innerHTML=S.party.map(x=>`<div class="row"><div><div class="rowName">${x.name}</div><div class="small">武 ${x.atk}　防 ${x.def}　智 ${x.int}　速 ${x.agi}</div></div><div>${x.hp}/${x.max}<div class="small">策 ${x.sp}/${x.maxSp}</div></div></div>`).join('');$('#overlay').classList.add('on')}
$('#new').onclick=()=>{S=state();show('#world');hud();map();ac();bgm();fx('sel')};$('#continue').onclick=load;$('#soundToggle').onclick=audioToggle;$('#soundBtn').onclick=audioToggle;$('#actionBtn').onclick=inspect;$('#hintBtn').onclick=()=>wm(`目前任務：${QUEST[S.quest]}`);$('#menuBtn').onclick=menu;$('#close').onclick=()=>$('#overlay').classList.remove('on');$('#save').onclick=save;$('#food').onclick=()=>{if(!S.food)return toast('軍糧不足');S.food--;S.party.forEach(x=>{x.hp=Math.min(x.max,x.hp+Math.floor(x.max*.4));x.sp=Math.min(x.maxSp,x.sp+8)});hud();menu();fx('heal')};
$$('[data-d]').forEach(b=>b.onclick=()=>{let d=b.dataset.d;move(d==='l'?-1:d==='r'?1:0,d==='u'?-1:d==='d'?1:0)});$$('[data-c]').forEach(b=>b.onclick=()=>cmd(b.dataset.c));audioUI();if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
})();
