const assert=require('node:assert/strict');
const fs=require('node:fs');
const {webkit}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright':'playwright');
(async()=>{
const browser=await webkit.launch({headless:true});const page=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:1,hasTouch:true,isMobile:true});
const errors=[],failed=[],checks=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)failed.push(r.url());});
const base=process.env.V12_BASE_URL||'http://127.0.0.1:8123';
const snap=async name=>{await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));return page.screenshot({path:`docs/v12/campaign-${name}.png`});};
async function dialogs(){while(await page.locator('#storyDialog').isVisible())await page.click('#advanceDialog');}
async function walk(goal){await page.evaluate(()=>__Campaign.state.encounter.safeSteps=999);const dirs=await page.evaluate(goal=>__Campaign.route(__Campaign.state,goal),goal);assert.ok(dirs,'walkable route');for(const dir of dirs)await page.click(`[data-dir=${dir}]`);}
async function mapIs(name){await page.waitForFunction(name=>__Campaign.state?.map===name,name);}
async function quickVictory(){await page.evaluate(()=>{__Campaign.battle.state.enemies.forEach(e=>e.hp=1);__Campaign.battle.emit();});while(!(await page.evaluate(()=>!!__Campaign.battle.state.result))){await page.waitForFunction(()=>__Campaign.battle.state.phase==='command'||__Campaign.battle.state.phase==='ended');if(await page.evaluate(()=>__Campaign.battle.state.result))break;await page.click('[data-cmd=attack]');const id=await page.evaluate(()=>__Campaign.battle.state.enemies.find(e=>e.hp>0).id);await page.click(`[data-id=${id}]`);}await page.waitForFunction(()=>__Campaign.state.pending===null);}
async function reloadJourney(){await page.reload();await page.waitForFunction(()=>window.__Campaign);assert.equal(await page.locator('#loadJourney').isEnabled(),true);await page.click('#loadJourney');}

await page.goto(base+'/?qa');await page.waitForFunction(()=>window.__Campaign);await snap('title-390x844');assert.equal(await page.locator('#loadJourney').isDisabled(),true);checks.push('new title + empty save');
await page.click('#startNew');await dialogs();await mapIs('xinye');await page.waitForFunction(()=>__Campaign.audio.source?.buffer);assert.equal(await page.evaluate(()=>__Campaign.audio.mode),'town');await snap('xinye-390x844');checks.push('new journey + opening dialogue + original town audio');
await page.click('#waypoint');await mapIs('overworld');checks.push('south gate transitions to overworld');
await page.evaluate(()=>__Campaign.startBattle('patrol'));assert.equal(await page.locator('.unit').count(),7);await page.click('[data-cmd=attack]');await page.click('[data-id=pikeman]');await page.waitForFunction(()=>__Campaign.battle.state.actor===1&&__Campaign.battle.state.phase==='command');const hp=await page.evaluate(()=>__Campaign.battle.state.enemies[0].hp);
await reloadJourney();assert.equal(await page.evaluate(()=>__Campaign.battle.state.actor),1);assert.equal(await page.evaluate(()=>__Campaign.battle.state.enemies[0].hp),hp);await snap('resumed-battle');checks.push('V12 patrol + command checkpoint reload');
const oldGold=await page.evaluate(()=>__Campaign.state.gold);await quickVictory();assert.equal(await page.evaluate(()=>__Campaign.state.gold),oldGold+91);await page.click('#replay');assert.equal(await page.locator('#worldScene').isVisible(),true);await reloadJourney();assert.equal(await page.evaluate(()=>__Campaign.state.gold),oldGold+91);checks.push('victory returns rewards once and reloads as exploration');
await walk({x:15,y:4});await mapIs('longzhong');await walk({x:6,y:5});await page.click('#interact');await dialogs();assert.equal(await page.evaluate(()=>__Campaign.state.story.stage),1);await snap('longzhong-dialogue-complete');await reloadJourney();assert.equal(await page.evaluate(()=>__Campaign.state.story.stage),1);checks.push('Longzhong conversation + objective persistence');
await walk({x:7,y:9});await mapIs('overworld');await walk({x:7,y:8});await mapIs('xinye');await dialogs();assert.equal(await page.evaluate(()=>__Campaign.state.story.stage),2);checks.push('return to Xinye opens preparation phase');
await walk({x:4,y:3});await page.click('#interact');assert.equal(await page.locator('#shopDialog').isVisible(),true);await snap('shop');await page.locator('.shop-row').filter({hasText:'皮甲'}).getByRole('button').click();assert.equal(await page.evaluate(()=>__Campaign.state.inventory.leatherArmor),1);await page.click('#closeShop');await page.click('#openCamp');await page.click('[data-tab=inventory]');await page.locator('.item-row').filter({hasText:'皮甲'}).getByRole('button').click();await page.locator('.target-hero').filter({hasText:'關羽'}).click();assert.equal(await page.evaluate(()=>__Campaign.state.party[1].armor),'leatherArmor');checks.push('purchase + explicit hero equipment assignment');
await page.evaluate(()=>__Campaign.state.party[0].hp=100);await page.locator('.item-row').filter({hasText:'軍糧'}).getByRole('button').click();await page.locator('.target-hero').filter({hasText:'劉備'}).click();assert.equal(await page.evaluate(()=>__Campaign.state.party[0].hp),1700);await page.click('[data-tab=formation]');await page.locator('.formation-choice').filter({hasText:'魚鱗'}).click();assert.equal(await page.evaluate(()=>__Campaign.state.formation),'魚鱗');await snap('camp');const xy=await page.evaluate(()=>[__Campaign.state.x,__Campaign.state.y]);await page.keyboard.press('ArrowDown');assert.deepEqual(await page.evaluate(()=>[__Campaign.state.x,__Campaign.state.y]),xy);await page.click('#closeCamp');checks.push('inventory use + formation + overlay blocks exploration');
await walk({x:10,y:3});await page.click('#interact');assert.ok(await page.evaluate(()=>__Campaign.state.party.every(p=>p.hp===p.maxHp&&p.sp===p.maxSp)));checks.push('inn fully restores HP/SP');
for(const [w,h,safe] of [[390,844,false],[393,852,false],[390,664,false],[390,844,true]]){await page.setViewportSize({width:w,height:h});await page.evaluate(safe=>{document.querySelector('#campaign').style.paddingTop=safe?'47px':'0px';document.querySelector('#campaign').style.paddingBottom=safe?'34px':'0px';},safe);const g=await page.evaluate(()=>({width:document.documentElement.scrollWidth,buttons:[...document.querySelectorAll('#worldScene button')].map(e=>{const r=e.getBoundingClientRect();return {x:r.x,y:r.y,w:r.width,h:r.height};}),map:document.querySelector('#worldMap').getBoundingClientRect().height}));assert.ok(g.width<=w);assert.ok(g.map>=150);for(const r of g.buttons){assert.ok(r.x>=0&&r.x+r.w<=w+.1);assert.ok(r.y>=0&&r.y+r.h<=h+.1);}await snap(`${w}x${h}${safe?'-safe':''}`);checks.push(`exploration layout ${w}x${h}${safe?' simulated safe areas':''}`);}
await page.setViewportSize({width:390,height:844});await page.evaluate(()=>{document.querySelector('#campaign').style.paddingTop='0px';document.querySelector('#campaign').style.paddingBottom='0px';});
await walk({x:8,y:11});await mapIs('overworld');await walk({x:22,y:8});await mapIs('bowang');await walk({x:8,y:6});await dialogs();assert.equal(await page.locator('.unit').count(),8);await quickVictory();await page.click('#replay');assert.equal(await page.evaluate(()=>__Campaign.state.story.stage),3);checks.push('vanguard victory unlocks the final approach');
await walk({x:8,y:2});await dialogs();assert.equal(await page.locator('.unit').count(),10);assert.equal(await page.evaluate(()=>__Campaign.audio.mode),'boss');await snap('boss');await quickVictory();assert.equal(await page.evaluate(()=>__Campaign.state.story.clear),true);await page.click('#replay');await snap('chapter-ending');await dialogs();await reloadJourney();assert.equal(await page.evaluate(()=>__Campaign.state.story.stage),4);assert.equal(await page.evaluate(()=>__Campaign.state.pending),null);checks.push('exact Golden cast + chapter victory + ending + persistent completion');
await page.evaluate(()=>{__Campaign.startBattle('boss');__Campaign.battle.state.party.forEach(p=>p.hp=1);__Campaign.battle.enemyTurn();});await page.waitForFunction(()=>__Campaign.battle.state.result?.win===false);await page.click('#replay');await mapIs('xinye');assert.ok(await page.evaluate(()=>__Campaign.state.party.every(p=>p.hp>0)));checks.push('defeat safely retreats with recoverable party');
await page.click('#openCamp');await page.click('[data-tab=journal]');await page.getByRole('button',{name:'保存並返回標題'}).click();assert.equal(await page.locator('#titleScene').isVisible(),true);await page.click('#startNew');assert.equal(await page.locator('#newDialog').isVisible(),true);await page.click('#cancelNew');checks.push('return to title + new journey confirmation');
assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);
fs.writeFileSync('docs/v12/campaign-browser-qa.json',JSON.stringify({engine:'Playwright WebKit 26.5 on Linux',physicalIPhone:false,checks,errors,failed},null,2));console.log(JSON.stringify({checks:checks.length,errors,failed}));await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
