import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {GoldenBattle} from '../../src/v12/battle.js';
import {MAPS,FIFTH_MAPS,nextObjective,retreatCamp,chapterNumber} from '../../src/v12/chapter-five.js';
import {newCampaign,normalizeCampaign,beginChapterTwo,provisionConvoy,beginChapterThree,agreeAlliance,beginChapterFour,orderSupplyEscort,beginChapterFive,orderFortDefense,battleState,storeCheckpoint,resolveEncounter,route,buyItem,equipItem} from '../../src/v12/campaign-state.js';
function cleared(){const s=newCampaign();Object.assign(s.story,{stage:19,chapter4Complete:true,chapter3Complete:true,chapter2Complete:true,supplySecured:true});s.map='changshatown';Object.assign(s,MAPS.changshatown.start);return s;}
function ordered(){const s=cleared();assert.equal(beginChapterFive(s),true);assert.equal(orderFortDefense(s),true);return s;}
function win(s,kind){const b=battleState(s,kind);storeCheckpoint(s,kind,b);assert.equal(resolveEncounter(s,kind,b,true),true);return b;}
test('V12.4.1 saves continue with five heroes, equipment, formation, resources and damage intact',()=>{const s=cleared();s.version='12.4';s.gold=1234;s.party[0].hp=721;s.party[1].armor='scaleArmor';s.inventory.ration=7;s.formation='魚鱗';const r=normalizeCampaign(s);assert.equal(beginChapterFive(r),true);assert.equal(r.map,'jianglingfort');assert.equal(r.story.stage,20);assert.equal(chapterNumber(r),5);assert.equal(r.gold,1234);assert.equal(r.party[0].hp,721);assert.equal(r.party[1].armor,'scaleArmor');assert.equal(r.inventory.ration,7);assert.equal(r.formation,'魚鱗');assert.equal(beginChapterFive(r),false);});
test('fourth completion never downgrades stages 20–24; incomplete and pending journeys cannot continue',()=>{for(let stage=20;stage<=24;stage++){const s=cleared();s.story.stage=stage;s.map=stage===24?'forttown':'jianglingfort';const r=normalizeCampaign(s);assert.equal(r.story.stage,stage);assert.equal(r.story.chapter4Complete,true);assert.equal(r.story.chapter5Complete,stage===24);}const s=cleared();s.pending={kind:'jingPatrol'};assert.equal(beginChapterFive(s),false);s.pending=null;s.story.stage=18;assert.equal(beginChapterFive(s),false);});
test('fifth map exits, points, services and objective routes all remain reachable',()=>{for(const [map,m] of Object.entries(FIFTH_MAPS)){const s=ordered();s.map=map;Object.assign(s,m.start);assert.equal(m.rows.length,m.height);assert.ok(m.rows.every(r=>r.length===m.width));if(m.exit)assert.ok(route(s,m.exit),map);if(m.points)for(let y=0;y<m.height;y++)for(let x=0;x<m.width;x++)if(m.points[m.rows[y][x]])assert.ok(route(s,{x,y}),map);for(const n of m.npcs||[])assert.ok([[0,1],[0,-1],[1,0],[-1,0]].some(([dx,dy])=>route(s,{x:n.x+dx,y:n.y+dy})),map+':'+n.id);}for(const [map,stage] of [['jianglingfort',20],['beaconpost',21],['convoypost',21],['jianglinggate',22]]){const s=ordered();s.map=map;s.story.stage=stage;Object.assign(s,MAPS[map].start);assert.ok(route(s,nextObjective(s)),map);}});
test('both preparation orders reach stage 22; convoy supplies and orders apply once',()=>{for(const kinds of [['signalDefense','convoyDefense'],['convoyDefense','signalDefense']]){const s=ordered(),before=s.inventory.ration;assert.equal(orderFortDefense(s),false);for(const kind of kinds){const b=win(s,kind);assert.equal(resolveEncounter(s,kind,b,true),false);}assert.equal(s.story.stage,22);assert.equal(s.inventory.ration,before+2);assert.deepEqual(normalizeCampaign(s).story.defensePlans,['beacon','convoy']);}});
test('signal effect and command checkpoint retain damaged HP, exact debuff, actor and guards on reload',()=>{const s=ordered();win(s,'signalDefense');win(s,'convoyDefense');s.story.stage=23;const baseline=battleState({...s,story:{...s.story,defensePlans:[]}},'jianglingSiege'),b=battleState(s,'jianglingSiege');assert.equal(new Set(b.enemies.map(e=>e.id)).size,5);assert.equal(b.enemies[1].archetype,'xuhuang');for(let i=0;i<5;i++)assert.equal(b.enemies[i].atk,baseline.enemies[i].atk-12);b.enemies[0].hp-=327;b.enemies[0].atk-=12;b.actor=2;b.round=3;b.guard.add('liubei');storeCheckpoint(s,'jianglingSiege',b);const r=normalizeCampaign(s),again=battleState(r,'jianglingSiege');assert.equal(again.enemies[0].hp,b.enemies[0].hp);assert.equal(again.enemies[0].atk,b.enemies[0].atk);assert.equal(again.actor,2);assert.equal(again.round,3);assert.equal(again.guard.has('liubei'),true);assert.equal(again.enemyFaction,'魏軍');});
test('premature fifth maps and already completed battle checkpoints cannot bypass the quest',()=>{for(const [map,stage] of [['jianglingfort',19],['beaconpost',20],['convoypost',20],['jianglinggate',21],['forttown',23]]){const s=cleared();s.story.stage=stage;s.map=map;assert.notEqual(normalizeCampaign(s).map,map);}for(const [kind,stage] of [['signalDefense',20],['convoyDefense',20],['jianglingSiege',22],['jianglingSiege',24]]){const s=cleared();s.story.stage=stage;storeCheckpoint(s,kind,battleState(s,kind));assert.equal(normalizeCampaign(s).pending,null);}const s=ordered();win(s,'signalDefense');storeCheckpoint(s,'signalDefense',battleState(s,'signalDefense'));assert.equal(normalizeCampaign(s).pending,null);});
test('defeat preserves preparations and spending; final victory returns to permanent services',()=>{const s=ordered();win(s,'signalDefense');win(s,'convoyDefense');s.story.stage=23;const b=battleState(s,'jianglingSiege');b.gold=240;b.rations=2;storeCheckpoint(s,'jianglingSiege',b);resolveEncounter(s,'jianglingSiege',b,false);assert.equal(s.map,'jianglingfort');assert.equal(s.gold,120);assert.equal(s.inventory.ration,2);assert.equal(s.story.stage,23);assert.deepEqual(s.story.defensePlans,['beacon','convoy']);win(s,'jianglingSiege');assert.equal(s.map,'forttown');assert.equal(s.story.stage,24);assert.equal(retreatCamp(s),'forttown');assert.equal(normalizeCampaign(s).story.stage,24);});
test('twelve seeded five-chapter journeys win with real combat stats and available camp recovery',async()=>{
 const reports=[];
 for(let seed=1;seed<=12;seed++){
  let random=seed;const rng=()=>((random=(random*1664525+1013904223)>>>0)/4294967296),s=newCampaign(),report={seed,battles:[]};s.story.stage=2;buyItem(s,'leatherArmor');equipItem(s,'liubei','leatherArmor');const rest=()=>s.party.forEach(p=>{p.hp=p.maxHp;p.sp=p.maxSp;});
  async function fight(kind){const b=new GoldenBattle({initialState:battleState(s,kind),rng,timeline:{effect(){},hurt(){},wait:async()=>{},attack:async(id,hit)=>hit(),cast:async(id,hit)=>hit()},audio:{sfx(){},start(){}}});storeCheckpoint(s,kind,b.state);let actions=0;
   while(!b.state.result&&actions++<400){if(kind==='bridge'){b.command('defend');while(b.state.phase!=='command'&&!b.state.result)await new Promise(r=>setImmediate(r));continue;}const p=b.actor(),t=b.state.enemies.filter(e=>e.hp>0).sort((a,z)=>a.hp-z.hp)[0],low=b.state.party.filter(p=>p.hp>0).sort((a,z)=>a.hp/a.maxHp-z.hp/z.maxHp)[0];let side='enemy',index=b.state.enemies.indexOf(t);if(p.int>=70&&p.sp>=7&&low.hp<low.maxHp*.5){b.command('tactic');b.skill('heal');side='ally';index=b.state.party.indexOf(low);}else if(b.state.rations>0&&low.hp<low.maxHp*.28){b.command('item');side='ally';index=b.state.party.indexOf(low);}else if(p.id==='kongming'&&p.sp>=6){b.command('tactic');b.skill('fire');}else b.command('attack');await b.target(side,index);}
   assert.equal(b.state.result?.win,true,`seed ${seed}, ${kind}`);assert.equal(resolveEncounter(s,kind,b.state,true),true);assert.equal(resolveEncounter(s,kind,b.state,true),false);report.battles.push({kind,rounds:b.state.round,actions,survivors:s.party.filter(p=>p.hp>0).length});
  }
  await fight('vanguard');await fight('boss');beginChapterTwo(s);rest();while(s.inventory.ration<2)assert.equal(buyItem(s,'ration'),null);provisionConvoy(s);await fight('rescueWest');rest();await fight('rescueEast');rest();s.story.stage=8;await fight('bridge');beginChapterThree(s);rest();agreeAlliance(s);for(const kind of seed%2?['windward','fireships']:['fireships','windward']){await fight(kind);rest();}s.story.stage=13;await fight('redcliff');beginChapterFour(s);rest();orderSupplyEscort(s);await fight('supplyEscort');rest();s.story.stage=18;await fight('changsha');assert.equal(s.story.stage,19);assert.equal(s.map,'changshatown');assert.equal(normalizeCampaign(s).story.stage,19);if(seed===1)fs.writeFileSync('docs/v12/chapter5-start-save.json',JSON.stringify({...s,version:'12.4'},null,2));beginChapterFive(s);rest();orderFortDefense(s);for(const kind of seed%2?['signalDefense','convoyDefense']:['convoyDefense','signalDefense']){await fight(kind);rest();}s.story.stage=23;await fight('jianglingSiege');assert.equal(s.story.stage,24);assert.equal(s.map,'forttown');assert.equal(normalizeCampaign(s).story.stage,24);reports.push(report);
 }
 fs.writeFileSync('docs/v12/chapter5-combat-qa.json',JSON.stringify({modifiedCombatStats:false,animationClock:'instant test clock',campRecovery:true,journeys:reports},null,2));
});
