const assert=require('node:assert/strict'),fs=require('node:fs');const {webkit}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright':'playwright');
(async()=>{
const browser=await webkit.launch({headless:true}),page=await browser.newPage({viewport:{width:390,height:844},hasTouch:true,isMobile:true});const errors=[],failed=[],checks=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)failed.push(r.url());});const base=process.env.V12_BASE_URL||'http://127.0.0.1:8123';
const shot=async name=>{await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));await page.screenshot({path:`docs/v12/chapter3-${name}.png`});};
async function dialogs(){while(await page.locator('#storyDialog').isVisible())await page.click('#advanceDialog');}
async function walk(goal){await page.evaluate(()=>__Campaign.state.encounter.safeSteps=999);const path=await page.evaluate(g=>__Campaign.route(__Campaign.state,g),goal);assert.ok(path,JSON.stringify(goal));for(const dir of path)await page.click(`[data-dir=${dir}]`);}
async function reload(){await page.reload();await page.waitForFunction(()=>window.__Campaign);await page.click('#loadJourney');}
async function shortWin(){await page.evaluate(()=>{__Campaign.battle.state.enemies.forEach(e=>e.hp=1);__Campaign.battle.emit();});while(!await page.evaluate(()=>__Campaign.battle.state.result)){await page.waitForFunction(()=>['command','ended'].includes(__Campaign.battle.state.phase));if(await page.evaluate(()=>__Campaign.battle.state.result))break;await page.click('[data-cmd=attack]');const id=await page.evaluate(()=>__Campaign.battle.state.enemies.find(e=>e.hp>0).id);await page.click(`[data-id=${id}]`);}await page.click('#replay');}
await page.goto(base+'/?qa');await page.waitForFunction(()=>window.__Campaign);const fixture=JSON.parse(fs.readFileSync('docs/v12/chapter3-start-save.json'));await page.evaluate(s=>localStorage.setItem('sanguo-kongming-v12-campaign',JSON.stringify(s)),fixture);await reload();assert.equal(await page.evaluate(()=>__Campaign.state.story.stage),9);assert.equal(await page.evaluate(()=>__Campaign.state.gold),fixture.gold);await page.click('#waypoint');await dialogs();assert.equal(await page.evaluate(()=>__Campaign.state.map),'alliedcamp');assert.equal(await page.evaluate(()=>__Campaign.state.party[0].armor),fixture.party[0].armor);await shot('camp-390x844');checks.push('actual-stat V12.2 completion fixture continues with saved party, gold and equipment');
await walk({x:8,y:11});await walk({x:23,y:12});assert.equal(await page.evaluate(()=>__Campaign.state.map),'riverworld');assert.match(await page.locator('#worldMessage').textContent(),/盟約/);await walk({x:12,y:11});await walk({x:8,y:8});await page.click('#interact');assert.match(await page.locator('#storyPortrait').getAttribute('src'),/zhouyu/);await shot('alliance');await dialogs();assert.equal(await page.evaluate(()=>__Campaign.state.story.stage),11);checks.push('alliance gate + Zhou Yu independent portrait and NPC + chapter-three journal');
await walk({x:8,y:11});await walk({x:25,y:8});assert.equal(await page.evaluate(()=>__Campaign.state.map),'riverworld');assert.match(await page.locator('#worldMessage').textContent(),/準備/);await walk({x:22,y:3});await walk({x:8,y:5});await shot('wind-altar');await page.click('#interact');await dialogs();await shortWin();await reload();assert.deepEqual(await page.evaluate(()=>__Campaign.state.story.plans),['wind']);assert.equal(await page.evaluate(()=>__Campaign.state.story.stage),11);checks.push('decision gate + wind preparation combat + one preparation flag survives reload');
await walk({x:8,y:15});await walk({x:23,y:12});await walk({x:6,y:7});await shot('shipyard');await page.click('#interact');await dialogs();await page.click('[data-cmd=attack]');await page.click('[data-id=pikeman]');await page.waitForFunction(()=>__Campaign.battle.state.actor===1&&__Campaign.battle.state.phase==='command');const enemyHp=await page.evaluate(()=>__Campaign.battle.state.enemies.find(e=>e.id==='pikeman').hp);await reload();assert.equal(await page.evaluate(()=>__Campaign.state.pending.kind),'fireships');assert.equal(await page.evaluate(()=>__Campaign.battle.state.enemies.find(e=>e.id==='pikeman').hp),enemyHp);await shortWin();assert.equal(await page.evaluate(()=>__Campaign.state.story.stage),12);checks.push('fire-ship battle checkpoint preserves damaged enemy + both plans unlock decision');
await walk({x:8,y:15});await walk({x:12,y:11});await walk({x:11,y:5});await page.click('#interact');assert.ok(await page.evaluate(()=>__Campaign.state.party.every(p=>p.hp===p.maxHp&&p.sp===p.maxSp)));await walk({x:8,y:11});await walk({x:25,y:8});await walk({x:8,y:11});await page.click('#interact');await page.click('#advanceDialog');assert.match(await page.locator('#storyPortrait').getAttribute('src'),/xuhuang/);await dialogs();await page.waitForFunction(()=>__Campaign.audio.mode==='naval'&&__Campaign.audio.source?.buffer);assert.equal(await page.locator('.unit').count(),10);assert.ok(await page.evaluate(()=>__Campaign.battle.state.enemies.every(e=>e.hp===Math.floor(e.maxHp*.8))));assert.match(await page.locator('#stage').getAttribute('style'),/redcliff/);await shot('battle-390x844');checks.push('camp recovery + Xu Huang production art + ten units + naval score + twenty-percent preparation benefit');
await page.click('[data-cmd=attack]');await page.click('[data-id=xuhuang]');await page.waitForFunction(()=>__Campaign.battle.state.actor===1&&__Campaign.battle.state.phase==='command');const savedHp=await page.evaluate(()=>__Campaign.battle.state.enemies[0].hp);await reload();assert.equal(await page.evaluate(()=>__Campaign.battle.state.enemies[0].hp),savedHp);assert.equal(await page.evaluate(()=>__Campaign.state.story.stage),13);checks.push('red-cliff checkpoint reload does not apply the preparation damage twice');
const before=await page.evaluate(()=>__Campaign.state.gold);let actions=0;
while(!await page.evaluate(()=>__Campaign.battle.state.result)){await page.waitForFunction(()=>['command','ended'].includes(__Campaign.battle.state.phase));if(await page.evaluate(()=>__Campaign.battle.state.result))break;assert.ok(actions++<400);const choice=await page.evaluate(()=>{const b=__Campaign.battle,s=b.state,p=b.actor(),low=s.party.filter(p=>p.hp>0).sort((a,z)=>a.hp/a.maxHp-z.hp/z.maxHp)[0],t=s.enemies.filter(e=>e.hp>0).sort((a,z)=>a.hp-z.hp)[0];if(p.int>=70&&p.sp>=7&&low.hp<low.maxHp*.5)return {cmd:'tactic',skill:'heal',id:low.id};if(s.rations>0&&low.hp<low.maxHp*.28)return {cmd:'item',id:low.id};if(p.id==='kongming'&&p.sp>=6)return {cmd:'tactic',skill:'fire',id:t.id};return {cmd:'attack',id:t.id};});await page.click(`[data-cmd=${choice.cmd}]`);if(choice.skill)await page.locator('#skills button').filter({hasText:choice.skill==='heal'?'聖雨':'火攻'}).click();await page.click(`[data-id=${choice.id}]`);await page.waitForFunction(()=>['command','ended'].includes(__Campaign.battle.state.phase));}
assert.equal(await page.evaluate(()=>__Campaign.battle.state.result.win),true);const earned=await page.evaluate(()=>__Campaign.battle.state.result.gold);assert.equal(await page.evaluate(()=>__Campaign.state.gold),before+earned);await page.click('#replay');await shot('ending');await dialogs();await reload();assert.equal(await page.evaluate(()=>__Campaign.state.story.stage),14);assert.equal(await page.evaluate(()=>__Campaign.state.map),'jiangling');assert.equal(await page.evaluate(()=>__Campaign.state.gold),before+earned);checks.push('unmodified-stat full boss victory + Zhou Yu ending + Jiangling completion + reward once after reload');
await page.click('#openCamp');await page.click('[data-tab=journal]');assert.match(await page.locator('#campBody').textContent(),/江陵/);await page.locator('#campBody button').filter({hasText:'返回江陵'}).click();assert.equal(await page.evaluate(()=>__Campaign.state.map),'jiangling');checks.push('chapter-three journal retreat hub preserves completed stages');
for(const [w,h,safe] of [[390,844,false],[393,852,false],[390,664,false],[390,844,true]]){await page.setViewportSize({width:w,height:h});await page.evaluate(s=>{document.querySelector('#campaign').style.paddingTop=s?'47px':'0px';document.querySelector('#campaign').style.paddingBottom=s?'34px':'0px';},safe);const g=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth,buttons:[...document.querySelectorAll('#worldScene button')].map(e=>{const r=e.getBoundingClientRect();return {x:r.x,y:r.y,w:r.width,h:r.height};})}));assert.equal(g.overflow,false);for(const r of g.buttons){assert.ok(r.x>=0&&r.x+r.w<=w+.1&&r.y>=0&&r.y+r.h<=h+.1);assert.ok(r.h>=44);}await shot(`${w}x${h}${safe?'-safe':''}`);checks.push(`third-chapter layout ${w}x${h}${safe?' safe areas':''}`);}
assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);fs.writeFileSync('docs/v12/chapter3-browser-qa.json',JSON.stringify({engine:'Playwright WebKit 26.5 on Linux',physicalIPhone:false,preparationFlowStatsModified:true,finalBossStatsModified:false,bossActions:actions,checks,errors,failed},null,2));console.log(JSON.stringify({checks:checks.length,errors,failed}));await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
