const assert=require('node:assert/strict'),fs=require('node:fs');
const {webkit}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright':'playwright');
(async()=>{
const browser=await webkit.launch({headless:true}),page=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:3,hasTouch:true,isMobile:true});
const errors=[],failed=[],checks=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)failed.push(r.url());});const base=process.env.V12_BASE_URL||'http://127.0.0.1:8123';
async function shot(name,proof=false){await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await page.screenshot({path:'docs/v12/chapter5-'+name+'.png'});if(proof)console.log('V12_PROOF_'+name.toUpperCase()+' '+(await page.screenshot({type:'jpeg',quality:70,scale:'css'})).toString('base64'));}
async function dialogs(){while(await page.locator('#storyDialog').isVisible())await page.click('#advanceDialog');}
async function walk(goal){await page.evaluate(()=>__Campaign.state.encounter.safeSteps=999);const path=await page.evaluate(g=>__Campaign.route(__Campaign.state,g),goal);assert.ok(path,JSON.stringify(goal));for(const dir of path)await page.click('[data-dir='+dir+']');}
async function reload(){await page.reload();await page.waitForFunction(()=>window.__Campaign);await page.click('#loadJourney');}
async function win(){let actions=0;while(!await page.evaluate(()=>__Campaign.battle.state.result)){await page.waitForFunction(()=>['command','ended'].includes(__Campaign.battle.state.phase));if(await page.evaluate(()=>__Campaign.battle.state.result))break;assert.ok(actions++<400);
const choice=await page.evaluate(()=>{const b=__Campaign.battle,s=b.state,p=b.actor(),low=s.party.filter(p=>p.hp>0).sort((a,z)=>a.hp/a.maxHp-z.hp/z.maxHp)[0],target=s.enemies.filter(e=>e.hp>0).sort((a,z)=>a.hp-z.hp)[0];if(p.int>=70&&p.sp>=7&&low.hp<low.maxHp*.5)return {cmd:'tactic',skill:'聖雨',id:low.id};if(s.rations>0&&low.hp<low.maxHp*.28)return {cmd:'item',id:low.id};if(p.id==='kongming'&&p.sp>=6)return {cmd:'tactic',skill:'火攻',id:target.id};return {cmd:'attack',id:target.id};});
await page.click('[data-cmd='+choice.cmd+']');if(choice.skill)await page.locator('#skills button').filter({hasText:choice.skill}).click();await page.click('[data-id='+choice.id+']');await page.waitForFunction(()=>['command','ended'].includes(__Campaign.battle.state.phase));}
assert.equal(await page.evaluate(()=>__Campaign.battle.state.result.win),true);return actions;}
async function bounds(scene){for(const [w,h,safe] of [[390,844,false],[393,852,false],[390,664,false],[390,844,true]]){await page.setViewportSize({width:w,height:h});await page.evaluate(({scene,safe})=>{const e=document.querySelector(scene==='#battle'?'#battle':'#campaign');e.style.paddingTop=safe?'47px':'0px';e.style.paddingBottom=safe?'34px':'0px';},{scene,safe});await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
const g=await page.evaluate(scene=>({overflow:document.documentElement.scrollWidth>innerWidth,buttons:[...document.querySelectorAll(scene+' button')].filter(e=>!e.hidden&&e.offsetWidth&&e.offsetHeight).map(e=>{const r=e.getBoundingClientRect();return {x:r.x,y:r.y,w:r.width,h:r.height};}),stage:document.querySelector('#stage').getBoundingClientRect().toJSON(),sprites:__Campaign.renderer?[...__Campaign.renderer.positions.values()]:[],canvas:{w:document.querySelector('#worldMap').width,rect:document.querySelector('#worldMap').getBoundingClientRect().toJSON()}}),scene);
assert.equal(g.overflow,false);for(const r of g.buttons){assert.ok(r.x>=0&&r.x+r.w<=w+.1&&r.y>=0&&r.y+r.h<=h+.1,JSON.stringify(r));if(scene!=='#battle'||r.h>30)assert.ok(r.h>=44);}
if(scene==='#battle')for(const p of g.sprites){assert.ok(p.x>=0&&p.x+p.w<=g.stage.width+.1&&p.y>=0&&p.y+p.h<=g.stage.height+.1);assert.ok(p.h<=p.rowH-25+.1);}
else assert.equal(g.canvas.w,Math.round(Math.min(g.canvas.rect.width,g.canvas.rect.height)*3));
await shot((scene==='#battle'?'battle':'camp')+'-'+w+'x'+h+(safe?'-safe':''));checks.push(scene+' bounds/DPR '+w+'x'+h+(safe?' safe':''));
}
await page.setViewportSize({width:390,height:844});await page.evaluate(scene=>{const e=document.querySelector(scene==='#battle'?'#battle':'#campaign');e.style.paddingTop='0px';e.style.paddingBottom='0px';},scene);}
await page.goto(base+'/?qa');await page.waitForFunction(()=>window.__Campaign);assert.match(await page.locator('.chapter-seal').textContent(),/五章/);await shot('title');
const fixture=JSON.parse(fs.readFileSync('docs/v12/chapter5-start-save.json'));await page.evaluate(s=>localStorage.setItem('sanguo-kongming-v12-campaign',JSON.stringify(s)),fixture);await reload();assert.equal(await page.evaluate(()=>__Campaign.state.story.stage),19);assert.equal(await page.locator('#waypoint').textContent(),'續章');await page.click('#waypoint');await dialogs();assert.equal(await page.evaluate(()=>__Campaign.state.story.stage),20);assert.equal(await page.evaluate(()=>__Campaign.state.map),'jianglingfort');assert.deepEqual(await page.evaluate(()=>__Campaign.state.party),fixture.party);assert.equal(await page.evaluate(()=>__Campaign.state.gold),fixture.gold);await shot('camp',true);checks.push('real four-chapter clear fixture continues without resetting party, gold or gear');
await bounds('#worldScene');
await walk({x:8,y:11});await walk({x:15,y:4});assert.equal(await page.evaluate(()=>__Campaign.state.map),'fortworld');assert.match(await page.locator('#worldMessage').textContent(),/軍令/);await walk({x:24,y:10});assert.equal(await page.evaluate(()=>__Campaign.state.map),'fortworld');await walk({x:24,y:6});assert.equal(await page.evaluate(()=>__Campaign.state.map),'fortworld');assert.match(await page.locator('#worldMessage').textContent(),/準備/);checks.push('preparation destinations and city gate lock before orders');
await walk({x:4,y:12});await walk({x:8,y:8});await page.click('#interact');await dialogs();assert.equal(await page.evaluate(()=>__Campaign.state.story.stage),21);await reload();assert.equal(await page.evaluate(()=>__Campaign.state.story.stage),21);checks.push('Kongming order survives reload without chapter-four flag downgrade');
await walk({x:8,y:11});await walk({x:15,y:4});await walk({x:8,y:5});await shot('beacon');await page.click('#interact');await dialogs();assert.ok(await page.evaluate(()=>__Campaign.battle.state.enemies.every(e=>e.hp===e.maxHp)));await page.click('[data-cmd=attack]');await page.click('[data-id=pikeman]');await page.waitForFunction(()=>__Campaign.battle.state.actor===1&&__Campaign.battle.state.phase==='command');const hp=await page.evaluate(()=>__Campaign.battle.state.enemies[0].hp);await reload();assert.equal(await page.evaluate(()=>__Campaign.state.pending.kind),'signalDefense');assert.equal(await page.evaluate(()=>__Campaign.battle.state.enemies[0].hp),hp);const signalActions=await win();await page.click('#replay');await reload();assert.deepEqual(await page.evaluate(()=>__Campaign.state.story.defensePlans),['beacon']);await page.click('#interact');assert.equal(await page.locator('#storyDialog').isVisible(),false);checks.push('unmodified signal battle, damaged checkpoint and one-time preparation survive reload');
await walk({x:8,y:15});await walk({x:24,y:6});assert.equal(await page.evaluate(()=>__Campaign.state.map),'fortworld');assert.match(await page.locator('#worldMessage').textContent(),/兩路/);checks.push('city gate remains locked after only one preparation');
await walk({x:4,y:12});await walk({x:11,y:5});await page.click('#interact');assert.ok(await page.evaluate(()=>__Campaign.state.party.every(p=>p.hp===p.maxHp&&p.sp===p.maxSp)));await walk({x:8,y:11});await walk({x:24,y:10});await walk({x:8,y:7});await shot('convoy');await page.click('#interact');await dialogs();const supplies=await page.evaluate(()=>__Campaign.state.inventory.ration);assert.ok(await page.evaluate(()=>__Campaign.battle.state.enemies.every(e=>e.hp===e.maxHp)));const convoyActions=await win(),used=await page.evaluate(()=>__Campaign.battle.state.rations);await page.click('#replay');assert.equal(await page.evaluate(()=>__Campaign.state.inventory.ration),used+2);await reload();assert.equal(await page.evaluate(()=>__Campaign.state.inventory.ration),used+2);assert.equal(await page.evaluate(()=>__Campaign.state.story.stage),22);await page.click('#interact');assert.equal(await page.locator('#storyDialog').isVisible(),false);checks.push('unmodified convoy battle, two supplies exactly once and both preparation flags restored');
await walk({x:8,y:15});await walk({x:4,y:12});await walk({x:11,y:5});await page.click('#interact');await walk({x:8,y:11});await walk({x:24,y:6});await walk({x:8,y:7});await shot('gate');await page.click('#interact');assert.match(await page.locator('#storyPortrait').getAttribute('src'),/kongming/);await dialogs();await page.waitForFunction(()=>__Campaign.audio.mode==='fortress'&&__Campaign.audio.source?.buffer);assert.equal(await page.locator('.unit').count(),10);assert.ok(await page.evaluate(()=>__Campaign.battle.state.enemies.every(e=>e.hp===e.maxHp)));assert.match(await page.locator('#stage').getAttribute('style'),/jiangling/);assert.match(await page.locator('#battle h1').textContent(),/江陵/);await shot('battle',true);checks.push('new production background, original decoded fortress score and full-stat five-versus-five cast');
await bounds('#battle');
await page.click('[data-cmd=attack]');await page.click('[data-id=caoren]');await page.waitForFunction(()=>__Campaign.battle.state.actor===1&&__Campaign.battle.state.phase==='command');const saved=await page.evaluate(()=>({hp:__Campaign.battle.state.enemies[0].hp,atk:__Campaign.battle.state.enemies[0].atk}));await reload();assert.deepEqual(await page.evaluate(()=>({hp:__Campaign.battle.state.enemies[0].hp,atk:__Campaign.battle.state.enemies[0].atk})),saved);assert.equal(await page.evaluate(()=>__Campaign.state.story.stage),23);checks.push('city battle HP and preparation attack modifier checkpoint restored exactly');
const before=await page.evaluate(()=>__Campaign.state.gold),bossActions=await win(),earned=await page.evaluate(()=>__Campaign.battle.state.result.gold);assert.equal(await page.evaluate(()=>__Campaign.state.gold),before+earned);await page.click('#replay');await shot('ending');await dialogs();await reload();assert.equal(await page.evaluate(()=>__Campaign.state.story.stage),24);assert.equal(await page.evaluate(()=>__Campaign.state.map),'forttown');assert.equal(await page.evaluate(()=>__Campaign.state.gold),before+earned);assert.equal(await page.locator('#waypoint').textContent(),'路標');checks.push('unmodified full city victory, ending, stage-24 clear and once-only reward survive reload');
await page.click('#openCamp');await page.click('[data-tab=journal]');assert.match(await page.locator('#campBody').textContent(),/江陵/);await page.locator('#campBody button').filter({hasText:'返回江陵'}).click();assert.equal(await page.evaluate(()=>__Campaign.state.map),'forttown');await walk({x:11,y:5});await page.click('#interact');assert.ok(await page.evaluate(()=>__Campaign.state.party.every(p=>p.hp===p.maxHp&&p.sp===p.maxSp)));await walk({x:4,y:5});await page.click('#interact');assert.equal(await page.locator('#shopDialog').isVisible(),true);assert.match(await page.locator('#shopDialog small').textContent(),/江陵/);await page.click('#closeShop');checks.push('permanent fifth chapter journal retreat, clinic and shop remain playable');
assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);fs.writeFileSync('docs/v12/chapter5-browser-qa.json',JSON.stringify({engine:'Playwright WebKit on Linux',physicalIPhone:false,combatStatsModified:false,fixture:'generated by twelve real-stat complete five-chapter seeded journeys',signalActions,convoyActions,bossActions,checks,errors,failed},null,2));console.log(JSON.stringify({chapter5Checks:checks.length,signalActions,convoyActions,bossActions,errors,failed}));await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
