const assert=require('node:assert/strict'),fs=require('node:fs');const {webkit}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright':'playwright');
(async()=>{
const browser=await webkit.launch({headless:true}),page=await browser.newPage({viewport:{width:390,height:844},hasTouch:true,isMobile:true});const errors=[],failed=[],checks=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)failed.push(r.url());});const base=process.env.V12_BASE_URL||'http://127.0.0.1:8123';
const shot=async name=>{await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));await page.screenshot({path:`docs/v12/chapter2-${name}.png`});};
async function dialogs(){while(await page.locator('#storyDialog').isVisible())await page.click('#advanceDialog');}
async function walk(goal){await page.evaluate(()=>__Campaign.state.encounter.safeSteps=999);const path=await page.evaluate(g=>__Campaign.route(__Campaign.state,g),goal);assert.ok(path);for(const dir of path)await page.click(`[data-dir=${dir}]`);}
async function reload(){await page.reload();await page.waitForFunction(()=>window.__Campaign);await page.click('#loadJourney');}
async function win(){await page.evaluate(()=>{__Campaign.battle.state.enemies.forEach(e=>e.hp=1);__Campaign.battle.emit();});while(!await page.evaluate(()=>__Campaign.battle.state.result)){await page.waitForFunction(()=>['command','ended'].includes(__Campaign.battle.state.phase));if(await page.evaluate(()=>__Campaign.battle.state.result))break;await page.click('[data-cmd=attack]');const id=await page.evaluate(()=>__Campaign.battle.state.enemies.find(e=>e.hp>0).id);await page.click(`[data-id=${id}]`);}await page.click('#replay');}
await page.goto(base+'/?qa');await page.waitForFunction(()=>window.__Campaign);await page.evaluate(async()=>{const {newCampaign,SAVE_KEY}=await import('./src/v12/campaign-state.js?v=12.2');const s=newCampaign();s.version='12.1';s.story={stage:4,clear:true,boss:true};s.gold=777;s.inventory.ration=0;s.party[1].armor='scaleArmor';localStorage.setItem(SAVE_KEY,JSON.stringify(s));});await reload();assert.equal(await page.evaluate(()=>__Campaign.state.gold),777);assert.equal(await page.locator('#waypoint').textContent(),'續章');await page.click('#waypoint');await dialogs();assert.equal(await page.evaluate(()=>__Campaign.state.map),'refugecamp');assert.equal(await page.evaluate(()=>__Campaign.state.party[1].armor),'scaleArmor');await shot('camp-390x844');checks.push('V12.1 clear save migrates and enters chapter two with equipment/resources');
await walk({x:8,y:8});await page.click('#interact');assert.equal(await page.evaluate(()=>__Campaign.state.story.stage),5);assert.match(await page.locator('#worldMessage').textContent(),/兩份軍糧/);await walk({x:4,y:3});await page.click('#interact');for(let i=0;i<2;i++)await page.locator('.shop-row').filter({hasText:'軍糧'}).getByRole('button').click();await page.click('#closeShop');await walk({x:8,y:8});await page.click('#interact');await dialogs();assert.equal(await page.evaluate(()=>__Campaign.state.story.stage),6);assert.equal(await page.evaluate(()=>__Campaign.state.inventory.ration),0);checks.push('provision gate + buying supplies + exactly-once consumption');
await walk({x:8,y:11});await walk({x:15,y:5});assert.equal(await page.evaluate(()=>__Campaign.state.map),'changban');await walk({x:4,y:6});await page.click('#interact');await dialogs();await win();assert.deepEqual(await page.evaluate(()=>__Campaign.state.story.rescued),['west']);await reload();assert.deepEqual(await page.evaluate(()=>__Campaign.state.story.rescued),['west']);await shot('first-rescue');checks.push('west rescue + battle return + persistent completion');
await walk({x:11,y:11});await page.click('#interact');await dialogs();await page.click('[data-cmd=attack]');await page.click('[data-id=pikeman]');await page.waitForFunction(()=>__Campaign.battle.state.actor===1&&__Campaign.battle.state.phase==='command');const hp=await page.evaluate(()=>__Campaign.battle.state.enemies[0].hp);await reload();assert.equal(await page.evaluate(()=>__Campaign.state.pending.kind),'rescueEast');assert.equal(await page.evaluate(()=>__Campaign.battle.state.enemies[0].hp),hp);await win();assert.equal(await page.evaluate(()=>__Campaign.state.story.stage),7);checks.push('east rescue checkpoint + reload + both families unlock ferry');
await walk({x:8,y:15});await walk({x:23,y:9});assert.equal(await page.evaluate(()=>__Campaign.state.map),'ferry');await walk({x:8,y:9});await shot('ferry');await page.click('#interact');await dialogs();await page.waitForFunction(()=>__Campaign.audio.mode==='bridge'&&__Campaign.audio.source?.buffer);assert.equal(await page.locator('.unit').count(),9);assert.equal(await page.evaluate(()=>__Campaign.battle.state.holdRounds),4);assert.match(await page.locator('#stage').getAttribute('style'),/changban/);await shot('bridge-390x844');checks.push('Cao Chun production art + river battlefield + original bridge music + four-round objective');
await page.click('[data-cmd=defend]');await page.waitForFunction(()=>__Campaign.battle.state.phase==='command'&&__Campaign.battle.state.actor===1);await reload();assert.equal(await page.evaluate(()=>__Campaign.battle.state.guard.has('liubei')),true);assert.equal(await page.evaluate(()=>__Campaign.battle.state.holdRounds),4);checks.push('guard and hold objective survive battle checkpoint reload');
const before=await page.evaluate(()=>__Campaign.state.gold);while(!await page.evaluate(()=>__Campaign.battle.state.result)){await page.waitForFunction(()=>['command','ended'].includes(__Campaign.battle.state.phase));if(await page.evaluate(()=>__Campaign.battle.state.result))break;await page.click('[data-cmd=defend]');await page.waitForFunction(()=>['command','ended'].includes(__Campaign.battle.state.phase));}
assert.equal(await page.evaluate(()=>__Campaign.battle.state.result.win),true);assert.equal(await page.evaluate(()=>__Campaign.battle.state.round),4);assert.ok(await page.evaluate(()=>__Campaign.battle.state.enemies.every(e=>e.hp===e.maxHp)));const earned=await page.evaluate(()=>__Campaign.battle.state.result.gold);assert.equal(await page.evaluate(()=>__Campaign.state.gold),before+earned);await page.click('#replay');await shot('ending');await dialogs();assert.equal(await page.evaluate(()=>__Campaign.state.map),'jiangxia');await reload();assert.equal(await page.evaluate(()=>__Campaign.state.story.stage),9);assert.equal(await page.evaluate(()=>__Campaign.state.gold),before+earned);checks.push('real four-round defense victory with live enemies + ending + rewards once + reload');
for(const [w,h,safe] of [[390,844,false],[393,852,false],[390,664,false],[390,844,true]]){await page.setViewportSize({width:w,height:h});await page.evaluate(s=>{document.querySelector('#campaign').style.paddingTop=s?'47px':'0px';document.querySelector('#campaign').style.paddingBottom=s?'34px':'0px';},safe);const g=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth,buttons:[...document.querySelectorAll('#worldScene button')].map(e=>{const r=e.getBoundingClientRect();return {x:r.x,y:r.y,w:r.width,h:r.height};})}));assert.equal(g.overflow,false);for(const r of g.buttons){assert.ok(r.x>=0&&r.x+r.w<=w+.1&&r.y>=0&&r.y+r.h<=h+.1);assert.ok(r.h>=44);}await shot(`${w}x${h}${safe?'-safe':''}`);checks.push(`chapter-two exploration layout ${w}x${h}${safe?' safe areas':''}`);}
assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);fs.writeFileSync('docs/v12/chapter2-browser-qa.json',JSON.stringify({engine:'Playwright WebKit 26.5 on Linux',physicalIPhone:false,rescueFlowStatsModified:true,bridgeCombatStatsModified:false,checks,errors,failed},null,2));console.log(JSON.stringify({checks:checks.length,errors,failed}));await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
