import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {GoldenBattle} from '../../src/v12/battle.js';
import {MAPS,FOURTH_MAPS,nextObjective,retreatCamp} from '../../src/v12/chapter-four.js';
import {newCampaign,normalizeCampaign,beginChapterTwo,provisionConvoy,beginChapterThree,agreeAlliance,beginChapterFour,orderSupplyEscort,battleState,storeCheckpoint,resolveEncounter,route,buyItem,equipItem} from '../../src/v12/campaign-state.js';
function cleared(){const s=newCampaign();Object.assign(s.story,{stage:14,chapter2Complete:true,chapter3Complete:true,plans:['wind','ships']});s.map='jiangling';Object.assign(s,MAPS.jiangling.start);return s;}
function ordered(){const s=cleared();assert.equal(beginChapterFour(s),true);assert.equal(orderSupplyEscort(s),true);return s;}
test('V12.3 completion continues with party, inventory, gear, formation and gold intact',()=>{const s=cleared();s.version='12.3';s.gold=1723;s.party[0].hp=721;s.party[1].armor='scaleArmor';s.inventory.ration=7;s.formation='魚鱗';const r=normalizeCampaign(s);assert.equal(beginChapterFour(r),true);assert.equal(r.map,'jingcamp');assert.equal(r.story.stage,15);assert.equal(r.gold,1723);assert.equal(r.party[0].hp,721);assert.equal(r.party[1].armor,'scaleArmor');assert.equal(r.inventory.ration,7);assert.equal(r.formation,'魚鱗');assert.equal(beginChapterFour(r),false);});
test('pending battle prevents continuation and chapter-two/three complete flags never downgrade fourth stages',()=>{for(const stage of [15,16,17,18,19]){const s=cleared();s.story.stage=stage;s.map=stage===19?'changshatown':'jingcamp';const r=normalizeCampaign(s);assert.equal(r.story.stage,stage);assert.equal(r.story.chapter3Complete,true);assert.equal(r.story.chapter4Complete,stage===19);}const s=cleared();s.pending={kind:'navalPatrol'};assert.equal(beginChapterFour(s),false);});
test('every fourth map, exit, service NPC and all quest routes are reachable',()=>{for(const [map,m] of Object.entries(FOURTH_MAPS)){assert.equal(m.rows.length,m.height);assert.ok(m.rows.every(r=>r.length===m.width));const s=ordered();s.map=map;Object.assign(s,m.start);if(m.exit)assert.ok(route(s,m.exit),map);if(m.points)for(let y=0;y<m.height;y++)for(let x=0;x<m.width;x++)if(m.points[m.rows[y][x]])assert.ok(route(s,{x,y}),map+':'+x+','+y);for(const n of m.npcs||[])assert.ok([[0,1],[0,-1],[1,0],[-1,0]].some(([dx,dy])=>route(s,{x:n.x+dx,y:n.y+dy})),map+':'+n.id);}for(const [map,stage] of [['jingcamp',15],['grainpost',16],['changshagate',17]]){const s=ordered();s.map=map;s.story.stage=stage;Object.assign(s,MAPS[map].start);assert.ok(route(s,nextObjective(s)),map);}});
test('supply order and grain victory advance once, granting exactly two rations',()=>{const s=cleared();beginChapterFour(s);assert.equal(orderSupplyEscort(s),true);assert.equal(orderSupplyEscort(s),false);const b=battleState(s,'supplyEscort');b.rations=3;storeCheckpoint(s,'supplyEscort',b);assert.equal(resolveEncounter(s,'supplyEscort',b,true),true);assert.equal(s.story.stage,17);assert.equal(s.story.supplySecured,true);assert.equal(s.inventory.ration,5);assert.equal(resolveEncounter(s,'supplyEscort',b,true),false);assert.equal(normalizeCampaign(s).inventory.ration,5);});
test('five distinct enemy instances share guard production art while damaged HP, SP, actor and guard restore exactly',()=>{const s=ordered();s.story.stage=18;s.story.supplySecured=true;const b=battleState(s,'changsha');assert.equal(b.enemies.length,5);assert.equal(new Set(b.enemies.map(e=>e.id)).size,5);assert.equal(b.enemies[3].archetype,'pikeman');assert.equal(b.enemies[4].archetype,'archer');b.enemies[0].hp-=327;b.enemies[0].sp=1;b.actor=2;b.round=3;b.guard.add('liubei');b.rations=1;b.party[0].hp-=55;storeCheckpoint(s,'changsha',b);const r=normalizeCampaign(s),restored=battleState(r,'changsha');assert.equal(restored.enemies[0].hp,b.enemies[0].hp);assert.equal(restored.enemies[0].sp,1);assert.equal(restored.party[0].hp,b.party[0].hp);assert.equal(restored.actor,2);assert.equal(restored.round,3);assert.equal(restored.rations,1);assert.equal(restored.guard.has('liubei'),true);assert.equal(restored.enemyFaction,'守軍');});
test('premature maps, checkpoints and already completed quest checkpoints cannot bypass progression',()=>{for(const [map,stage] of [['jingcamp',14],['grainpost',15],['changshagate',16],['changshatown',18]]){const s=cleared();s.story.stage=stage;s.map=map;assert.notEqual(normalizeCampaign(s).map,map);}for(const [kind,stage] of [['supplyEscort',15],['changsha',17],['supplyEscort',17],['changsha',19]]){const s=cleared();s.story.stage=stage;storeCheckpoint(s,kind,battleState(s,kind));assert.equal(normalizeCampaign(s).pending,null);}});
test('defeat preserves supply and spending; victory returns to permanent Changsha hub',()=>{const s=ordered();s.story.stage=18;s.story.supplySecured=true;const b=battleState(s,'changsha');b.gold=240;b.rations=2;storeCheckpoint(s,'changsha',b);resolveEncounter(s,'changsha',b,false);assert.equal(s.map,'jingcamp');assert.equal(s.gold,120);assert.equal(s.inventory.ration,2);assert.equal(s.story.stage,18);assert.equal(s.story.supplySecured,true);assert.equal(retreatCamp(s),'jingcamp');const retry=battleState(s,'changsha');storeCheckpoint(s,'changsha',retry);resolveEncounter(s,'changsha',retry,true);assert.equal(s.map,'changshatown');assert.equal(s.story.stage,19);assert.equal(retreatCamp(s),'changshatown');const r=normalizeCampaign(s);assert.equal(r.story.stage,19);assert.equal(r.story.chapter3Complete,true);});
test('twelve seeded four-chapter journeys win with real combat stats and available camp recovery',async()=>{
 const reports=[];
 for(let seed=1;seed<=12;seed++){
  let random=seed;const rng=()=>((random=(random*1664525+1013904223)>>>0)/4294967296),s=newCampaign(),report={seed,battles:[]};s.story.stage=2;buyItem(s,'leatherArmor');equipItem(s,'liubei','leatherArmor');const rest=()=>s.party.forEach(p=>{p.hp=p.maxHp;p.sp=p.maxSp;});
  async function fight(kind){const b=new GoldenBattle({initialState:battleState(s,kind),rng,timeline:{effect(){},hurt(){},wait:async()=>{},attack:async(id,hit)=>hit(),cast:async(id,hit)=>hit()},audio:{sfx(){},start(){}}});storeCheckpoint(s,kind,b.state);let actions=0;
   while(!b.state.result&&actions++<400){if(kind==='bridge'){b.command('defend');while(b.state.phase!=='command'&&!b.state.result)await new Promise(r=>setImmediate(r));continue;}const p=b.actor(),t=b.state.enemies.filter(e=>e.hp>0).sort((a,z)=>a.hp-z.hp)[0],low=b.state.party.filter(p=>p.hp>0).sort((a,z)=>a.hp/a.maxHp-z.hp/z.maxHp)[0];let side='enemy',index=b.state.enemies.indexOf(t);if(p.int>=70&&p.sp>=7&&low.hp<low.maxHp*.5){b.command('tactic');b.skill('heal');side='ally';index=b.state.party.indexOf(low);}else if(b.state.rations>0&&low.hp<low.maxHp*.28){b.command('item');side='ally';index=b.state.party.indexOf(low);}else if(p.id==='kongming'&&p.sp>=6){b.command('tactic');b.skill('fire');}else b.command('attack');await b.target(side,index);}
   assert.equal(b.state.result?.win,true,`seed ${seed}, ${kind}`);assert.equal(resolveEncounter(s,kind,b.state,true),true);assert.equal(resolveEncounter(s,kind,b.state,true),false);report.battles.push({kind,rounds:b.state.round,actions,survivors:s.party.filter(p=>p.hp>0).length});
  }
  await fight('vanguard');await fight('boss');beginChapterTwo(s);rest();while(s.inventory.ration<2)assert.equal(buyItem(s,'ration'),null);provisionConvoy(s);await fight('rescueWest');rest();await fight('rescueEast');rest();s.story.stage=8;await fight('bridge');beginChapterThree(s);rest();agreeAlliance(s);for(const kind of seed%2?['windward','fireships']:['fireships','windward']){await fight(kind);rest();}s.story.stage=13;await fight('redcliff');if(seed===1)fs.writeFileSync('docs/v12/chapter4-start-save.json',JSON.stringify({...s,version:'12.3'},null,2));beginChapterFour(s);rest();orderSupplyEscort(s);await fight('supplyEscort');rest();s.story.stage=18;await fight('changsha');assert.equal(s.story.stage,19);assert.equal(s.map,'changshatown');assert.equal(normalizeCampaign(s).story.stage,19);reports.push(report);
 }
 fs.writeFileSync('docs/v12/chapter4-combat-qa.json',JSON.stringify({modifiedCombatStats:false,animationClock:'instant test clock',campRecovery:true,journeys:reports},null,2));
});
