import test from 'node:test';
import assert from 'node:assert/strict';
import {freshState,effective,damage,SKILLS} from '../../src/v12/rules.js';
import {GoldenBattle} from '../../src/v12/battle.js';
class Clock{constructor(){this.events=[];this.effects=[];}wait(){return Promise.resolve();}effect(...a){this.effects.push(a);}hurt(id,ko){this.events.push(['hurt',id,ko]);}async attack(id,hit){this.events.push([id,'anticipation']);this.events.push([id,'strike']);hit();this.events.push([id,'recover']);}async cast(id,hit){this.events.push([id,'cast']);hit();}}
const make=()=>new GoldenBattle({timeline:new Clock(),audio:{sfx(){},start(){}},rng:()=>.5});
test('Golden cast and V11 equipment/formation damage rules preserved',()=>{const s=freshState();assert.equal(s.party.length,5);assert.equal(s.enemies.length,5);assert.equal(effective(s.party[1]).atk,100);const t=s.enemies[0];const d=damage(s,effective(s.party[0]),t,1,false,true,()=>.5);assert.equal(d,339);assert.equal(t.hp,8800-d);});
test('guard reduces actual enemy damage, not merely its label',()=>{const a=freshState(),b=freshState();b.guard.add(b.party[0].id);const d=damage(a,a.enemies[0],a.party[0],.9,false,false,()=>.5);assert.equal(damage(b,b.enemies[0],b.party[0],.9,false,false,()=>.5),Math.floor(d*.55));});
test('cancel targeting neither spends SP nor consumes action',()=>{const b=make(),sp=b.actor().sp;b.command('tactic');b.skill('fire');b.cancel();assert.equal(b.actor().sp,sp);assert.equal(b.state.actor,0);assert.equal(b.state.phase,'command');});
test('double target activation resolves one attack and advances once',async()=>{const b=make(),hp=b.state.enemies[0].hp;b.command('attack');await Promise.all([b.target('enemy',0),b.target('enemy',0)]);assert.equal(b.state.actor,1);assert.equal(b.state.enemies[0].hp,hp-339);assert.deepEqual(b.timeline.events.slice(0,2),[['liubei','anticipation'],['liubei','strike']]);assert.ok(b.timeline.events.some(x=>x[1]==='recover'));});
test('invalid/dead target ignored; confirmed spell pays exactly once',async()=>{const b=make();b.command('tactic');b.skill('fire');await b.target('ally',0);assert.equal(b.actor().sp,24);await b.target('enemy',0);assert.equal(b.state.party[0].sp,19);assert.equal(b.state.actor,1);assert.equal(b.timeline.effects[0][1],'fire');});
test('heal caps HP and spends resources only on confirmation',async()=>{const b=make();b.state.party[1].hp-=100;b.command('tactic');b.skill('heal');await b.target('ally',1);assert.equal(b.state.party[1].hp,5000);assert.equal(b.state.party[0].sp,18);assert.equal(b.timeline.effects[0][2],'+100');});
test('unaffordable/unlearned spells rejected',()=>{const b=make();b.state.party[0].sp=0;b.command('tactic');for(const sk of SKILLS)b.skill(sk.id);assert.equal(b.state.phase,'skills');});
test('full ally round yields one enemy round, then unlocks commands',async()=>{const b=make();for(let i=0;i<5;i++){b.command('attack');await b.target('enemy',0);}assert.equal(b.state.round,2);assert.equal(b.state.actor,0);assert.equal(b.state.phase,'command');assert.ok(b.state.party.some(p=>p.hp<p.maxHp));});
test('defense survives all ally actions, clears only after enemy round',async()=>{const b=make();b.command('defend');await new Promise(r=>setImmediate(r));assert.ok(b.state.guard.has('liubei'));for(let i=1;i<5;i++){b.command('attack');await b.target('enemy',0);}assert.equal(b.state.guard.size,0);});
test('rush cannot hit a corpse and consumes whole party round',async()=>{const b=make();b.state.enemies[0].hp=1;b.command('rush');await b.target('enemy',0);assert.equal(b.state.enemies[0].hp,0);assert.equal(b.timeline.events.filter(x=>x[0]==='liubei'&&x[1]==='strike').length,1);assert.equal(b.state.round,2);});
test('victory awarded once, commands locked; defeat does not play victory',async()=>{const b=make();b.state.enemies.forEach((e,i)=>e.hp=i?0:1);b.command('attack');await b.target('enemy',0);assert.equal(b.state.phase,'ended');assert.equal(b.state.result.win,true);assert.equal(b.state.result.gold,1051);const gold=b.state.gold;b.command('attack');await b.target('enemy',0);assert.equal(b.state.gold,gold);const loss=make();loss.state.party.forEach(p=>p.hp=1);await loss.enemyTurn();assert.equal(loss.state.result.win,false);});
