import {getV8Music} from './v8/musicV8.js';
export class AudioSystem{
  constructor(){this.ctx=null;this.master=null;this.enabled=true;this.timer=null;this.step=0;this.mode='world';this.ready=false;this._starting=false;this._everUnlocked=false;this._gesture=()=>{if(this.enabled&&(!this.isReady()||this.ctx?.state!=='running'))this.unlock({chime:false,fromGesture:true})};document.addEventListener('pointerdown',this._gesture,{passive:true,capture:true});document.addEventListener('touchstart',this._gesture,{passive:true,capture:true});document.addEventListener('touchend',this._gesture,{passive:true,capture:true});document.addEventListener('keydown',this._gesture,{passive:true,capture:true});document.addEventListener('visibilitychange',()=>this._visibility());window.addEventListener('pageshow',()=>this._wakeAfterBackground());queueMicrotask(()=>this.emit())}
  emit(){try{document.dispatchEvent(new CustomEvent('sanguo-audio-state',{detail:{enabled:this.enabled,ready:this.isReady(),context:this.ctx?.state||'none',everUnlocked:this._everUnlocked}}))}catch{}}
  ensureContext(){if(!this.enabled)return null;const A=window.AudioContext||window.webkitAudioContext;if(!A)return null;if(!this.ctx||this.ctx.state==='closed'){try{if(navigator.audioSession&&'type'in navigator.audioSession)navigator.audioSession.type='playback'}catch{}this.ctx=new A({latencyHint:'interactive'});this.master=this.ctx.createGain();this.master.gain.value=.9;const comp=this.ctx.createDynamicsCompressor();comp.threshold.value=-20;comp.knee.value=14;comp.ratio.value=4;comp.attack.value=.003;comp.release.value=.18;this.master.connect(comp);comp.connect(this.ctx.destination);this.ctx.onstatechange=()=>{this.ready=this.ctx?.state==='running'&&this._everUnlocked;this.emit()}}return this.ctx}
  ensure(){return this.ensureContext()}isReady(){return !!(this.ctx&&this.ctx.state==='running'&&this.ready)}
  _prime(c){try{const b=c.createBuffer(1,1,22050),s=c.createBufferSource(),g=c.createGain();g.gain.value=.00001;s.buffer=b;s.connect(g);g.connect(this.master);s.start(0);const o=c.createOscillator(),og=c.createGain();o.type='square';o.frequency.value=220;og.gain.value=.00001;o.connect(og);og.connect(this.master);o.start(0);o.stop(c.currentTime+.02)}catch{}}
  async unlock({chime=false}={}){if(!this.enabled)return false;const c=this.ensureContext();if(!c)return false;try{this._prime(c);if(c.state!=='running')await c.resume();this._prime(c);this.ready=c.state==='running';this._everUnlocked=this._everUnlocked||this.ready;if(this.ready&&chime){this.tone(659,.08,'square',.07);this.tone(988,.11,'square',.06,.07)}this.emit();if(this.ready&&this.enabled&&!this.timer)this._beginMusic();return this.ready}catch{this.ready=false;this.emit();return false}}
  async test(){if(!this.enabled)this.enabled=true;const ok=await this.unlock({chime:true});if(ok&&!this.timer)this._beginMusic();return ok}
  tone(freq=440,dur=.08,type='square',vol=.05,delay=0,detune=0){if(!this.enabled)return;const c=this.ensureContext();if(!c||c.state!=='running')return;const o=c.createOscillator(),g=c.createGain(),t=c.currentTime+delay;o.type=type;o.frequency.setValueAtTime(freq,t);o.detune.value=detune;g.gain.setValueAtTime(Math.max(.0001,vol),t);g.gain.exponentialRampToValueAtTime(.0001,t+dur);o.connect(g);g.connect(this.master);o.start(t);o.stop(t+dur+.025)}
  noise(dur=.04,vol=.022,delay=0){const c=this.ensureContext();if(!c||c.state!=='running')return;const len=Math.max(1,Math.floor(c.sampleRate*dur)),buf=c.createBuffer(1,len,c.sampleRate),a=buf.getChannelData(0);for(let i=0;i<len;i++)a[i]=(Math.random()*2-1)*(1-i/len);const s=c.createBufferSource(),g=c.createGain(),t=c.currentTime+delay;s.buffer=buf;g.gain.setValueAtTime(vol,t);g.gain.exponentialRampToValueAtTime(.0001,t+dur);s.connect(g);g.connect(this.master);s.start(t)}
  hz(m){return 440*Math.pow(2,(m-69)/12)}
  sfx(name){if(!this.enabled)return;if(!this.isReady()){this.unlock({chime:false});return}const p={ui:[[76,.06,.06],[81,.08,.05]],move:[[72,.025,.023]],hit:[[49,.055,.065],[43,.09,.05]],cast:[[76,.07,.05],[81,.1,.045],[88,.13,.04]],heal:[[72,.1,.04],[76,.12,.038],[81,.16,.034]],buy:[[79,.06,.05],[84,.09,.045]],win:[[76,.08,.045],[81,.08,.045],[84,.1,.045],[88,.15,.04]],level:[[72,.07,.045],[76,.07,.045],[81,.08,.045],[88,.15,.04]],lose:[[64,.12,.05],[60,.15,.045],[55,.2,.04]]}[name]||[];p.forEach((x,i)=>this.tone(this.hz(x[0]),x[1],name==='lose'?'triangle':'square',x[2],i*.06));if(name==='hit')this.noise(.035,.025)}
  _musicData(){return getV8Music(this.mode)}
  _beginMusic(){this.stop();if(!this.enabled||!this.isReady())return;const q=this._musicData();this.step=0;const tick=()=>{if(!this.enabled||!this.isReady())return;const s=this.step,m=q.mel[s%q.mel.length],h=q.harm[s%q.harm.length],b=q.bass[Math.floor(s/2)%q.bass.length],ch=q.arp[Math.floor(s/4)%q.arp.length],dr=q.drum[s%q.drum.length];this.tone(this.hz(m),.105,'square',.034);if(s%2===0)this.tone(this.hz(h),.15,'square',.016,.012,7);this.tone(this.hz(b),.18,'triangle',.023);const a=ch[s%3];this.tone(this.hz(a+12),.04,'square',.009,.03);if(dr===1){this.noise(.04,.02);this.tone(this.hz(b-12),.04,'triangle',.019)}else if(dr===2){this.noise(.028,.015,.01)}else if(dr===3){this.noise(.018,.01,.015)}this.step++};tick();this.timer=setInterval(tick,q.tempo)}
  start(mode='world'){this.mode=mode;this.stop();if(!this.enabled)return;if(this.isReady()){this._beginMusic();return}if(this._starting)return;this._starting=true;this.unlock().then(ok=>{this._starting=false;if(ok&&this.enabled&&!this.timer)this._beginMusic()})}
  stop(){if(this.timer){clearInterval(this.timer);this.timer=null}}
  async toggle(){if(this.enabled&&!this.isReady())return this.test();if(this.enabled){this.enabled=false;this.stop();this.emit();return false}this.enabled=true;const ok=await this.test();this.emit();return ok}
  _visibility(){if(document.hidden){this.stop();this.ready=false;this.emit();return}this._wakeAfterBackground()}
  _wakeAfterBackground(){if(!this.enabled||!this.ctx||!this._everUnlocked)return;this.ctx.resume().then(()=>{this.ready=this.ctx.state==='running';this.emit();if(this.ready&&!this.timer)this._beginMusic()}).catch(()=>{this.ready=false;this.emit()})}
}