import {SKILLS,ENEMIES,FORMATIONS,ITEMS} from './data.js';
import {spriteData,portraitData} from './art.js';
const R=(a,b)=>Math.floor(Math.random()*(b-a+1))+a;
export class BattleSystem{
  constructor(ui,state,audio,onEnd){this.ui=ui;this.state=state;this.audio=audio;this.onEnd=onEnd;this.b=null}
  start(enemyIds,{boss=false,label='遭遇戰'}={}){const enemies=enemyIds.map(id=>{const e=structuredClone(ENEMIES[id]);return {...e,id,hp:e.maxHp,maxSp:Math.max(6,Math.floor(e.int/8)),sp:Math.max(6,Math.floor(e.int/8))}});this.b={enemies,actor:0,round:1,guard:new Set(),boss,label,select:null,pose:{}};this.render();this.msg(boss?'強敵出現！':'敵軍逼近！');this.nextActor()}
  effective(p){const w=ITEMS[p.weapon]||{},a=ITEMS[p.armor]||{};return {...p,atk:p.atk+(w.atk||0),def:p.def+(a.def||0),int:p.int+(w.int||0)+(a.int||0),agi:p.agi+(w.agi||0)+(a.agi||0)}}
  damage(attacker,target,mult=1,magic=false,isAlly=false){const fm=FORMATIONS[this.state.formation];let base=magic?(attacker.int*10-target.int*3):(attacker.atk*9-target.def*4);if(isAlly&&!magic)base*=fm.atk;let d=Math.max(90,Math.floor(base*mult*(.65+.35*(attacker.hp/attacker.maxHp))*R(88,114)/100));if(this.b.guard.has(target))d=Math.floor(d*.55);if(!isAlly)d=Math.floor(d*fm.def);target.hp=Math.max(0,target.hp-d);return d}
  render(){const b=this.b,u=this.ui;u.enemy.innerHTML=b.enemies.map((e,i)=>this.unitHtml(e,i,true)).join('');u.ally.innerHTML=this.state.party.map((p,i)=>this.unitHtml(p,i,false)).join('');u.round.textContent=`${b.label} · 第 ${b.round} 回合 · ${this.state.formation}陣`;const p=this.state.party[b.actor]||this.state.party.find(x=>x.hp>0);if(p){u.portrait.src=portraitData(p.id);const ep=this.effective(p);u.stats.innerHTML=`<b>${p.name}</b><br>Lv.${p.level}　EXP ${p.exp}<br>兵力 <span>${Math.max(0,p.hp)}/${p.maxHp}</span><br>策略 ${p.sp}/${p.maxSp}<br>武 ${ep.atk}　防 ${ep.def}<br>智 ${ep.int}　速 ${ep.agi}`;}if(b.select)this.activateTargets()}
  unitHtml(x,i,enemy){const key=enemy?x.archetype:x.id,pose=this.b.pose[`${enemy?'e':'a'}${i}`]||'idle';return `<div class="battle-unit ${enemy?'enemy':''} ${x.hp<=0?'dead':''}" data-side="${enemy?'enemy':'ally'}" data-idx="${i}"><img src="${spriteData(key,pose,this.b.round%2,3)}"><div class="unit-copy"><strong>${x.name}</strong><small>${Math.max(0,x.hp)}</small><div class="bar"><i style="width:${Math.max(0,x.hp/x.maxHp*100)}%"></i></div></div></div>`}
  msg(t){this.ui.msg.textContent=t}
  target(side,cb){this.b.select={side,cb};this.render();this.msg(side==='enemy'?'選擇敵軍目標。':'選擇我軍目標。')}
  activateTargets(){this.ui.root.querySelectorAll('.battle-unit').forEach(el=>{el.classList.remove('target');const idx=+el.dataset.idx;if(el.dataset.side===this.b.select.side){const unit=el.dataset.side==='enemy'?this.b.enemies[idx]:this.state.party[idx];if(unit.hp>0){el.classList.add('target');el.onclick=()=>{const cb=this.b.select.cb;this.b.select=null;cb(idx)}}}})}
  animate(side,idx,pose='hurt'){this.b.pose[`${side==='enemy'?'e':'a'}${idx}`]=pose;this.render();setTimeout(()=>{delete this.b.pose[`${side==='enemy'?'e':'a'}${idx}`];this.render()},280)}
  nextActor(){this.ui.skills.classList.remove('open');this.ui.cmds.classList.remove('hidden');let i=this.b.actor;while(i<this.state.party.length&&this.state.party[i].hp<=0)i++;if(i>=this.state.party.length)i=this.state.party.findIndex(p=>p.hp>0);if(i<0)return this.finish(false);this.b.actor=i;this.render();this.msg(`${this.state.party[i].name} 行動。`)}
  command(cmd){const p=this.state.party[this.b.actor],ep=this.effective(p);if(cmd==='attack')this.target('enemy',i=>{const e=this.b.enemies[i],d=this.damage(ep,e,1,false,true);this.audio.sfx('hit');this.animate('enemy',i);this.msg(`${p.name} 攻擊 ${e.name}，造成 ${d} 損失。`);this.afterAction()});
    else if(cmd==='rush')this.target('enemy',i=>{let total=0;for(const ally of this.state.party.filter(x=>x.hp>0)){total+=this.damage(this.effective(ally),this.b.enemies[i],.52,false,true)}this.audio.sfx('hit');this.animate('enemy',i);this.msg(`全軍總攻！${this.b.enemies[i].name} 損失 ${total}。`);this.afterAction(true)});
    else if(cmd==='tactic')this.showSkills();else if(cmd==='formation'){const fs=Object.keys(FORMATIONS),n=(fs.indexOf(this.state.formation)+1)%fs.length;this.state.formation=fs[n];this.audio.sfx('ui');this.msg(`改為 ${this.state.formation}陣：${FORMATIONS[this.state.formation].desc}`);this.afterAction()}
    else if(cmd==='item'){if((this.state.inventory.ration||0)<=0){this.msg('沒有軍糧。');return}this.target('ally',i=>{this.state.inventory.ration--;const t=this.state.party[i],h=Math.min(t.maxHp-t.hp,ITEMS.ration.heal);t.hp+=h;this.audio.sfx('heal');this.msg(`${t.name} 恢復 ${h} 兵力。`);this.afterAction()})}
    else if(cmd==='defend'){this.b.guard.add(p);this.msg(`${p.name} 採取防禦。`);this.afterAction()}
    else if(cmd==='flee'){if(this.b.boss){this.msg('Boss 戰無法撤退。');return}if(Math.random()<.62){this.onEnd({win:null,fled:true});}else{this.msg('撤退失敗！');setTimeout(()=>this.enemyTurn(),350)}}
  }
  showSkills(){const p=this.state.party[this.b.actor],ep=this.effective(p);this.ui.cmds.classList.add('hidden');this.ui.skills.classList.add('open');this.ui.skills.innerHTML=SKILLS.filter(s=>ep.int>=s.minInt).map(s=>`<button data-skill="${s.id}" ${p.sp<s.cost?'disabled':''}>${s.name} ${s.cost}</button>`).join('');this.ui.skills.querySelectorAll('button').forEach(b=>b.onclick=()=>this.cast(b.dataset.skill))}
  cast(id){const sk=SKILLS.find(s=>s.id===id),p=this.state.party[this.b.actor],ep=this.effective(p);if(!sk||p.sp<sk.cost)return;p.sp-=sk.cost;this.b.pose[`a${this.b.actor}`]='cast';this.audio.sfx(sk.type==='heal'?'heal':'cast');if(sk.type==='damage')this.target('enemy',i=>{const d=this.damage(ep,this.b.enemies[i],sk.power,true,true);this.animate('enemy',i);this.msg(`${p.name} 施展${sk.name}，造成 ${d} 損失。`);this.afterAction()});else if(sk.type==='heal')this.target('ally',i=>{const t=this.state.party[i],h=Math.min(t.maxHp-t.hp,Math.floor(ep.int*14+R(300,650)));t.hp+=h;this.msg(`${p.name} 施展${sk.name}，${t.name} 恢復 ${h}。`);this.afterAction()});else this.target('enemy',i=>{this.b.enemies[i].atk=Math.max(30,this.b.enemies[i].atk-12);this.msg(`${this.b.enemies[i].name} 攻擊下降。`);this.afterAction()})}
  afterAction(rush=false){this.render();if(this.b.enemies.every(e=>e.hp<=0))return this.finish(true);if(rush){setTimeout(()=>this.enemyTurn(),420);return}let n=this.b.actor+1;while(n<this.state.party.length&&this.state.party[n].hp<=0)n++;if(n<this.state.party.length){this.b.actor=n;setTimeout(()=>this.nextActor(),320)}else setTimeout(()=>this.enemyTurn(),420)}
  enemyTurn(){this.b.guard.clear();const order=this.b.enemies.map((e,i)=>[e,i]).filter(([e])=>e.hp>0).sort((a,b)=>b[0].agi-a[0].agi);let k=0;const go=()=>{if(k>=order.length){if(this.state.party.every(p=>p.hp<=0))return this.finish(false);this.b.actor=this.state.party.findIndex(p=>p.hp>0);this.b.round++;this.nextActor();return}const [e,ei]=order[k++],alive=this.state.party.map((p,i)=>[p,i]).filter(([p])=>p.hp>0),[t,ti]=alive[R(0,alive.length-1)],magic=e.int>75&&e.sp>=5&&Math.random()<.35;let d;if(magic){e.sp-=5;d=this.damage(e,t,1.12,true,false);this.audio.sfx('cast');this.msg(`${e.name} 施展計策！${t.name} 損失 ${d}。`)}else{d=this.damage(e,t,.9,false,false);this.audio.sfx('hit');this.msg(`${e.name} 攻擊 ${t.name}，造成 ${d}。`)}this.animate('ally',ti);setTimeout(go,360)};go()}
  finish(win){if(win){let gold=0,exp=0;for(const e of this.b.enemies){gold+=e.gold;exp+=e.exp}this.state.gold+=gold;const levelUps=[];for(const p of this.state.party){p.exp+=exp;while(p.exp>=p.level*100){p.exp-=p.level*100;p.level++;p.maxHp+=260;p.maxSp+=2;p.atk+=4;p.def+=3;p.int+=2;p.agi+=2;p.hp=p.maxHp;p.sp=p.maxSp;levelUps.push(p.name)}}this.audio.sfx(levelUps.length?'level':'win');setTimeout(()=>this.onEnd({win:true,gold,exp,levelUps,boss:this.b.boss}),500)}else{this.audio.sfx('lose');setTimeout(()=>this.onEnd({win:false}),500)}}
}
