import {SKILLS,ENEMIES,FORMATIONS,ITEMS} from './data.js';
import {BattleRenderer} from './v8/battleRenderer.js';
const R=(a,b)=>Math.floor(Math.random()*(b-a+1))+a;
export class BattleSystem{
  constructor(ui,state,audio,onEnd,cinematic=null){this.ui=ui;this.state=state;this.audio=audio;this.onEnd=onEnd;this.cinematic=cinematic;this.b=null;this.renderer=new BattleRenderer(ui,state,p=>this.effective(p))}
  start(enemyIds,{boss=false,label='遭遇戰'}={}){const enemies=enemyIds.map(id=>{const e=structuredClone(ENEMIES[id]);return {...e,id,hp:e.maxHp,maxSp:Math.max(6,Math.floor(e.int/8)),sp:Math.max(6,Math.floor(e.int/8))}});this.b={enemies,actor:0,round:1,guard:new Set(),boss,label,select:null,pose:{},animFrame:{},busy:false,xiahouSkillShown:false};this.render();this.msg(boss?'強敵出現！':'敵軍逼近！');this.nextActor()}
  effective(p){const w=ITEMS[p.weapon]||{},a=ITEMS[p.armor]||{};return {...p,atk:p.atk+(w.atk||0),def:p.def+(a.def||0),int:p.int+(w.int||0)+(a.int||0),agi:p.agi+(w.agi||0)+(a.agi||0)}}
  damage(attacker,target,mult=1,magic=false,isAlly=false){const fm=FORMATIONS[this.state.formation];let base=magic?(attacker.int*10-target.int*3):(attacker.atk*9-target.def*4);if(isAlly&&!magic)base*=fm.atk;let d=Math.max(90,Math.floor(base*mult*(.65+.35*(attacker.hp/attacker.maxHp))*R(88,114)/100));if(this.b.guard.has(target))d=Math.floor(d*.55);if(!isAlly)d=Math.floor(d*fm.def);target.hp=Math.max(0,target.hp-d);return d}
  render(){this.renderer.render(this.b);if(this.b.select)this.activateTargets()}
  msg(t){this.ui.msg.textContent=t}
  target(side,cb){if(this.b.busy)return;this.b.select={side,cb};this.render();this.msg(side==='enemy'?'選擇敵軍目標。':'選擇我軍目標。')}
  activateTargets(){this.ui.root.querySelectorAll('.battle-unit').forEach(el=>{el.classList.remove('target');const idx=+el.dataset.idx;if(el.dataset.side===this.b.select.side){const unit=el.dataset.side==='enemy'?this.b.enemies[idx]:this.state.party[idx];if(unit.hp>0){el.classList.add('target');el.onclick=()=>{const cb=this.b.select.cb;this.b.select=null;cb(idx)}}}})}
  unitEl(side,idx){return this.ui.root.querySelector(`.battle-unit[data-side="${side}"][data-idx="${idx}"]`)}
  fx(side,idx,kind,text=''){const el=this.unitEl(side,idx);if(!el)return;el.classList.add('impact');const f=document.createElement('span');f.className=`combat-fx fx-${kind}`;f.textContent=text;el.appendChild(f);setTimeout(()=>{f.remove();el.classList.remove('impact')},620)}
  sequence(side,idx,pose,frames=[0,1,2],speed=105,onFrame=null,onDone=null){const key=`${side==='enemy'?'e':'a'}${idx}`;this.b.busy=true;let n=0;const step=()=>{this.b.pose[key]=pose;this.b.animFrame[key]=frames[n];this.render();onFrame?.(n,frames[n]);n++;if(n<frames.length){setTimeout(step,speed);return}setTimeout(()=>{delete this.b.pose[key];delete this.b.animFrame[key];this.b.busy=false;this.render();onDone?.()},speed)};step()}
  hurt(side,idx,dmg=0,kind='hit'){const key=`${side==='enemy'?'e':'a'}${idx}`;this.b.pose[key]='hurt';this.b.animFrame[key]=0;this.render();this.fx(side,idx,kind,dmg?`-${dmg}`:'');setTimeout(()=>{this.b.animFrame[key]=1;this.render()},90);setTimeout(()=>{delete this.b.pose[key];delete this.b.animFrame[key];this.render()},260)}
  nextActor(){this.ui.skills.classList.remove('open');this.ui.cmds.classList.remove('hidden');let i=this.b.actor;while(i<this.state.party.length&&this.state.party[i].hp<=0)i++;if(i>=this.state.party.length)i=this.state.party.findIndex(p=>p.hp>0);if(i<0)return this.finish(false);this.b.actor=i;this.render();this.msg(`${this.state.party[i].name} 行動。`)}
  command(cmd){if(this.b.busy)return;const p=this.state.party[this.b.actor],ep=this.effective(p);
    if(cmd==='attack')this.target('enemy',i=>{const e=this.b.enemies[i],ai=this.b.actor;this.sequence('ally',ai,'attack',[0,1,2],95,n=>{if(n===1){const d=this.damage(ep,e,1,false,true);this.audio.sfx('hit');this.hurt('enemy',i,d,'slash');this.msg(`${p.name} 攻擊 ${e.name}，造成 ${d} 損失。`)}},()=>setTimeout(()=>this.afterAction(),120))});
    else if(cmd==='rush')this.target('enemy',i=>{this.b.busy=true;let total=0,actors=this.state.party.map((x,idx)=>[x,idx]).filter(([x])=>x.hp>0),k=0;const go=()=>{if(k>=actors.length){this.hurt('enemy',i,total,'burst');this.audio.sfx('hit');this.msg(`全軍總攻！${this.b.enemies[i].name} 損失 ${total}。`);setTimeout(()=>{this.b.busy=false;this.afterAction(true)},360);return}const [ally,ai]=actors[k++],key=`a${ai}`;let f=0;const frames=[0,1,2];const tick=()=>{this.b.pose[key]='attack';this.b.animFrame[key]=frames[f];this.render();if(f===1)total+=this.damage(this.effective(ally),this.b.enemies[i],.52,false,true);f++;if(f<frames.length)setTimeout(tick,70);else setTimeout(()=>{delete this.b.pose[key];delete this.b.animFrame[key];this.render();go()},65)};tick()};go()});
    else if(cmd==='tactic')this.showSkills();
    else if(cmd==='formation'){const fs=Object.keys(FORMATIONS),n=(fs.indexOf(this.state.formation)+1)%fs.length;this.state.formation=fs[n];this.audio.sfx('ui');this.msg(`改為 ${this.state.formation}陣：${FORMATIONS[this.state.formation].desc}`);this.ui.root.querySelector('.battle-stage')?.classList.add('formation-flash');setTimeout(()=>this.ui.root.querySelector('.battle-stage')?.classList.remove('formation-flash'),500);this.afterAction()}
    else if(cmd==='item'){if((this.state.inventory.ration||0)<=0){this.msg('沒有軍糧。');return}this.target('ally',i=>{this.state.inventory.ration--;const t=this.state.party[i],h=Math.min(t.maxHp-t.hp,ITEMS.ration.heal);t.hp+=h;this.audio.sfx('heal');this.fx('ally',i,'heal',`+${h}`);this.msg(`${t.name} 恢復 ${h} 兵力。`);this.afterAction()})}
    else if(cmd==='defend'){this.b.guard.add(p);this.fx('ally',this.b.actor,'guard','防');this.msg(`${p.name} 採取防禦。`);this.afterAction()}
    else if(cmd==='flee'){if(this.b.boss){this.msg('Boss 戰無法撤退。');return}if(Math.random()<.62){this.onEnd({win:null,fled:true});}else{this.msg('撤退失敗！');setTimeout(()=>this.enemyTurn(),350)}}
  }
  showSkills(){const p=this.state.party[this.b.actor],ep=this.effective(p);this.ui.cmds.classList.add('hidden');this.ui.skills.classList.add('open');this.ui.skills.innerHTML=SKILLS.filter(s=>ep.int>=s.minInt).map(s=>`<button data-skill="${s.id}" ${p.sp<s.cost?'disabled':''}><strong>${s.name}</strong><small>${s.cost} SP</small></button>`).join('');this.ui.skills.querySelectorAll('button').forEach(b=>b.onclick=()=>this.cast(b.dataset.skill))}
  tacticCutin(p,sk){return this.cinematic?.show({key:p.id,name:p.name,kicker:'軍師計策',text:sk.name,tone:'skill',duration:430})||Promise.resolve()}
  cast(id){if(this.b.busy)return;const sk=SKILLS.find(s=>s.id===id),p=this.state.party[this.b.actor],ep=this.effective(p);if(!sk||p.sp<sk.cost)return;p.sp-=sk.cost;
    if(sk.type==='damage')this.target('enemy',i=>{this.b.busy=true;this.tacticCutin(p,sk).then(()=>{this.b.busy=false;this.sequence('ally',this.b.actor,'cast',[0,1],130,n=>{if(n===1){this.fx('enemy',i,id,id==='thunder'?'雷':id==='fire'?'火':'術');const d=this.damage(ep,this.b.enemies[i],sk.power,true,true);this.audio.sfx('cast');this.hurt('enemy',i,d,id==='thunder'?'thunder':'fire');this.msg(`${p.name} 施展${sk.name}，造成 ${d} 損失。`)}},()=>setTimeout(()=>this.afterAction(),130))})});
    else if(sk.type==='heal')this.target('ally',i=>{this.b.busy=true;this.tacticCutin(p,sk).then(()=>{this.b.busy=false;this.sequence('ally',this.b.actor,'cast',[0,1],130,n=>{if(n===1){const t=this.state.party[i],h=Math.min(t.maxHp-t.hp,Math.floor(ep.int*14+R(300,650)));t.hp+=h;this.audio.sfx('heal');this.fx('ally',i,'heal',`+${h}`);this.msg(`${p.name} 施展${sk.name}，${t.name} 恢復 ${h}。`)}},()=>setTimeout(()=>this.afterAction(),120))})});
    else this.target('enemy',i=>{this.b.busy=true;this.tacticCutin(p,sk).then(()=>{this.b.busy=false;this.sequence('ally',this.b.actor,'cast',[0,1],130,n=>{if(n===1){this.b.enemies[i].atk=Math.max(30,this.b.enemies[i].atk-12);this.fx('enemy',i,'debuff','↓');this.audio.sfx('cast');this.msg(`${this.b.enemies[i].name} 攻擊下降。`)}},()=>setTimeout(()=>this.afterAction(),120))})})}
  afterAction(rush=false){this.render();if(this.b.enemies.every(e=>e.hp<=0))return this.finish(true);if(rush){setTimeout(()=>this.enemyTurn(),420);return}let n=this.b.actor+1;while(n<this.state.party.length&&this.state.party[n].hp<=0)n++;if(n<this.state.party.length){this.b.actor=n;setTimeout(()=>this.nextActor(),320)}else setTimeout(()=>this.enemyTurn(),420)}
  enemyTurn(){if(this.b.busy)return;this.b.guard.clear();const order=this.b.enemies.map((e,i)=>[e,i]).filter(([e])=>e.hp>0).sort((a,b)=>b[0].agi-a[0].agi);let k=0;const go=()=>{if(k>=order.length){if(this.state.party.every(p=>p.hp<=0))return this.finish(false);this.b.actor=this.state.party.findIndex(p=>p.hp>0);this.b.round++;this.nextActor();return}const [e,ei]=order[k++],alive=this.state.party.map((p,i)=>[p,i]).filter(([p])=>p.hp>0),[t,ti]=alive[R(0,alive.length-1)];const xiahou=e.archetype==='xiahoudun'&&Math.random()<.34;const magic=!xiahou&&e.int>75&&e.sp>=5&&Math.random()<.35;const perform=()=>{if(xiahou){this.sequence('enemy',ei,'attack',[0,1,2],100,n=>{if(n===1){const d=this.damage(e,t,1.38,false,false);this.audio.sfx('hit');this.hurt('ally',ti,d,'burst');this.msg(`夏侯惇施展「烈斬」！${t.name} 損失 ${d}。`)}},()=>setTimeout(go,190));return}this.sequence('enemy',ei,magic?'cast':'attack',magic?[0,1]:[0,1,2],magic?120:95,n=>{if(n===1){let d;if(magic){e.sp-=5;d=this.damage(e,t,1.12,true,false);this.audio.sfx('cast');this.fx('ally',ti,'enemycast','術');this.msg(`${e.name} 施展計策！${t.name} 損失 ${d}。`)}else{d=this.damage(e,t,.9,false,false);this.audio.sfx('hit');this.msg(`${e.name} 攻擊 ${t.name}，造成 ${d}。`)}this.hurt('ally',ti,d,magic?'enemycast':'slash')}},()=>setTimeout(go,170))};if(xiahou&&!this.b.xiahouSkillShown&&this.cinematic){this.b.xiahouSkillShown=true;this.cinematic.show({key:'xiahoudun',name:'夏侯惇',kicker:'魏軍猛將',text:'烈斬 · 破陣',tone:'boss',duration:560}).then(perform)}else perform()};go()}
  finish(win){if(win){let gold=0,exp=0;for(const e of this.b.enemies){gold+=e.gold;exp+=e.exp}this.state.gold+=gold;const levelUps=[];for(const p of this.state.party){p.exp+=exp;while(p.exp>=p.level*100){p.exp-=p.level*100;p.level++;p.maxHp+=260;p.maxSp+=2;p.atk+=4;p.def+=3;p.int+=2;p.agi+=2;p.hp=p.maxHp;p.sp=p.maxSp;levelUps.push(p.name)}}this.audio.sfx(levelUps.length?'level':'win');setTimeout(()=>this.onEnd({win:true,gold,exp,levelUps,boss:this.b.boss}),500)}else{this.audio.sfx('lose');setTimeout(()=>this.onEnd({win:false}),500)}}
}