import {PARTY_TEMPLATE,ITEMS,SHOP_STOCK,MAPS,STORY_TEXT,VERSION} from './data.js';
import {AudioSystem} from './audio.js';
import {saveGame,loadGame} from './save.js';
import {WorldSystem} from './world.js';
import {BattleSystem} from './battle.js';
import {CinematicSystem} from './cinematics.js';
import {portraitData} from './art.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const audio=new AudioSystem();const cinematic=new CinematicSystem($('#cutin'));let state=null,world=null,battle=null;
const ui={battle:{root:$('#battle'),ally:$('#allyList'),enemy:$('#enemyList'),round:$('#battleRound'),portrait:$('#portrait'),stats:$('#actorStats'),msg:$('#battleMsg'),skills:$('#skills'),cmds:$('#cmds')}};
const BIO={liubei:'仁德主將。劍術均衡，兼具智略與統御。',guanyu:'青龍偃月，長髯赤面。高武力重裝猛將。',zhangfei:'豹頭環眼，豪勇剛烈。爆發力最高的前鋒。',zhaoyun:'白袍銀槍，身法迅捷。高速度的全能武將。',kongming:'羽扇綸巾，智略無雙。擅長落雷、聖雨與擾亂。'};
function newState(){return {version:VERSION,map:'xinye',x:8,y:9,gold:500,formation:'鶴翼',party:structuredClone(PARTY_TEMPLATE),inventory:{ration:3,spiritTea:1},story:{stage:0,longzhong:false,returned:false,bowangGate:false,boss:false,clear:false},steps:0,lastSafe:{map:'xinye',x:8,y:9}}}
function show(id){$$('.screen').forEach(s=>s.classList.remove('on'));$(id).classList.add('on')}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('on');clearTimeout(e.t);e.t=setTimeout(()=>e.classList.remove('on'),1100)}
function msg(t){$('#worldMsg').textContent=t}
function quest(){const s=state.story.stage;return ['前往隆中拜訪孔明','返回新野整備，商店已開放','前往博望坡迎擊曹軍','深入博望坡擊敗夏侯惇','第一章完成'][s]||'自由探索'}
function refreshHUD(){const m=MAPS[state.map];$('#location').textContent=m.name;$('#gold').textContent=`金 ${state.gold}`;$('#formation').textContent=state.formation;$('#quest').textContent=`任務：${quest()}`;$('#soundState').textContent=`聲音 ${audio.enabled?'開':'關'}`}
function setupWorld(){world=new WorldSystem($('#worldCanvas'),state,onTile,msg);world.render();refreshHUD()}
function enterMap(id,x,y){state.map=id;const m=MAPS[id];state.x=x??m.start.x;state.y=y??m.start.y;if(id==='xinye')state.lastSafe={map:id,x:state.x,y:state.y};setupWorld();show('#world');audio.start('world');msg(`來到${m.name}。`)}
function onTile(ch){state.steps++;if(state.map==='overworld'&&['.','R'].includes(ch)&&Math.random()<.14){startEncounter()}if(state.map==='bowang'&&state.story.stage>=2&&!state.story.bowangGate&&state.y<=6){state.story.bowangGate=true;msg(STORY_TEXT.bowangIntro);setTimeout(()=>startBattle(['officer','pikeman','archer','scout','pikeman'],{label:'博望坡先鋒'}),450)}if(state.map==='bowang'&&state.story.bowangGate&&!state.story.boss&&state.y<=2){setTimeout(()=>{msg(STORY_TEXT.bossIntro);startBattle(['caoren','zhanghe','officer','archer','xiahoudun'],{boss:true,label:'博望坡決戰'})},350)}}
function startEncounter(){const sets=[['scout','pikeman','archer'],['pikeman','pikaman','officer'],['archer','scout','officer','pikeman']];const raw=sets[Math.floor(Math.random()*sets.length)],ids=raw.map(x=>x==='pikaman'?'pikeman':x);startBattle(ids,{label:'野外遭遇戰'})}
function launchBattle(ids,opt){show('#battle');audio.start(opt.boss?'boss':'battle');battle=new BattleSystem(ui.battle,state,audio,result=>endBattle(result,opt),cinematic);battle.start(ids,opt)}
function startBattle(ids,opt={}){if(opt.boss){show('#battle');audio.start('boss');cinematic.show({key:'xiahoudun',name:'夏侯惇',kicker:'魏軍先鋒 · 博望坡',text:'「劉備小兒，今日看你往哪裡逃！」',tone:'boss',duration:920}).then(()=>launchBattle(ids,opt));return}launchBattle(ids,opt)}
function endBattle(r,opt){if(r.win===null&&r.fled){enterMap(state.map,state.x,state.y);msg('成功撤退。');return}if(r.win){toast(`勝利！+${r.gold}金 / +${r.exp}EXP`);if(r.levelUps?.length)msg(`${r.levelUps.join('、')} 升級了！`);if(opt.boss){state.story.boss=true;state.story.clear=true;state.story.stage=4;cinematic.show({key:'kongming',name:'孔明',kicker:'博望坡 · 首戰告捷',text:'「火勢既起，曹軍鋒芒已挫。」',tone:'ally',duration:760}).then(showEnding);return}enterMap(state.map,state.x,state.y)}else{state.party.forEach(p=>{p.hp=p.maxHp;p.sp=p.maxSp});state.gold=Math.max(0,state.gold-120);enterMap(state.lastSafe.map,state.lastSafe.x,state.lastSafe.y);msg('戰敗後撤回新野整軍，損失部分軍資。')}}
function interact(){const m=MAPS[state.map];const n=world.nearbyNpc();if(n){if(n.id==='kongmingNpc'&&!state.story.longzhong){state.story.longzhong=true;state.story.stage=1;state.party.forEach(p=>{p.hp=p.maxHp;p.sp=p.maxSp});cinematic.show({key:'kongming',name:'孔明',kicker:'隆中 · 臥龍',text:'「曹軍不久將至，我已有一計。」',tone:'ally',duration:720});msg(STORY_TEXT.longzhong);audio.sfx('ui');refreshHUD();return}msg(n.dialog.join(' '));audio.sfx('ui');return}const ch=world.tileAt(state.x,state.y);if(state.map==='overworld'&&m.points?.[ch]){const p=m.points[ch];if(ch==='B'&&state.story.stage<2){msg('曹軍尚未逼近，現在前往博望坡沒有意義。');return}enterMap(p.to);return}if(state.map!=='overworld'&&m.exit&&state.x===m.exit.x&&state.y===m.exit.y){enterMap(m.exit.to,m.exit.toX,m.exit.toY);return}if(state.map==='xinye'){const cur=world.tileAt(state.x,state.y);if(cur==='S'){if(!state.story.longzhong){msg('商店尚未正式供應軍需。');return}openShop();return}if(cur==='I'){state.party.forEach(p=>{p.hp=p.maxHp;p.sp=p.maxSp});msg('在客棧休息，全隊恢復。');audio.sfx('heal');return}if(state.story.longzhong&&!state.story.returned){state.story.returned=true;state.story.stage=2;cinematic.show({key:'kongming',name:'孔明',kicker:'軍略 · 博望坡',text:'「坡道狹長，可誘敵深入，再以火攻破之。」',tone:'skill',duration:720});msg(STORY_TEXT.returned);refreshHUD();return}}msg('這裡沒有特別的事物。')}
function openShop(){const body=$('#shopBody');body.innerHTML=SHOP_STOCK.map(id=>{const it=ITEMS[id];return `<div class="shop-item"><div><strong>${it.name}</strong><div class="muted">${it.desc} · ${it.type==='weapon'?`攻+${it.atk||0}`:it.type==='armor'?`防+${it.def||0}`:'消耗品'}</div></div><button data-buy="${id}">${it.price}金</button></div>`}).join('');body.querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>buy(b.dataset.buy));$('#shopOverlay').classList.add('on')}
function buy(id){const it=ITEMS[id];if(state.gold<it.price){toast('金錢不足');return}state.gold-=it.price;if(it.type==='consumable')state.inventory[id]=(state.inventory[id]||0)+1;else{state.inventory[id]=(state.inventory[id]||0)+1;autoEquip(id)}audio.sfx('buy');refreshHUD();toast(`購入 ${it.name}`)}
function autoEquip(id){const it=ITEMS[id],slot=it.type;let best=state.party[0];if(id==='scholarRobe'||id==='featherFan')best=state.party.find(p=>p.id==='kongming')||best;else if(id.includes('Spear'))best=state.party.find(p=>p.id==='zhaoyun')||best;else if(id==='generalBlade')best=state.party.find(p=>p.id==='guanyu')||best;best[slot]=id;state.inventory[id]--}
function openMenu(tab='party'){renderMenu(tab);$('#menuOverlay').classList.add('on')}
function renderMenu(tab){if(tab==='party'){$('#menuBody').innerHTML=state.party.map(p=>{const w=ITEMS[p.weapon],a=ITEMS[p.armor];return `<div class="party-card"><img src="${portraitData(p.id)}" alt="${p.name}"><div><strong>${p.name} <small>${p.role}</small></strong><div class="muted">Lv.${p.level} · 兵力 ${p.hp}/${p.maxHp} · 策略 ${p.sp}/${p.maxSp}</div><div class="muted">武器 ${w?.name||'無'} / 防具 ${a?.name||'無'}</div></div><div class="party-stats">武${p.atk}<br>防${p.def}<br>智${p.int}</div></div>`}).join('');return}if(tab==='art'){$('#menuBody').innerHTML=state.party.map(p=>`<div class="codex-card"><img src="${portraitData(p.id)}" alt="${p.name}"><div><strong>${p.name}</strong><div class="epithet">${p.role}</div><div class="muted">${BIO[p.id]||''}</div></div></div>`).join('');return}$('#menuBody').innerHTML=Object.entries(state.inventory).filter(([,n])=>n>0).map(([id,n])=>`<div class="list-row"><div><strong>${ITEMS[id]?.name||id}</strong><div class="muted">${ITEMS[id]?.desc||''}</div></div><div>×${n}</div></div>`).join('')||'<div class="muted">沒有物品</div>'}
function showEnding(){$('#endingText').textContent=STORY_TEXT.chapterClear;$('#endingOverlay').classList.add('on');saveGame(state)}
function startNew(){state=newState();show('#world');setupWorld();msg(STORY_TEXT.intro);audio.ensure();audio.start('world')}
function continueGame(){const s=loadGame();if(!s){toast('沒有存檔');return}state=s;show('#world');setupWorld();msg('已讀取進度。');audio.ensure();audio.start('world')}
$('#newBtn').onclick=startNew;$('#continueBtn').onclick=continueGame;$('#aBtn').onclick=interact;$('#bBtn').onclick=()=>openMenu();$('#soundBtn').onclick=()=>{audio.toggle();refreshHUD()};$('#partyTab').onclick=()=>renderMenu('party');$('#inventoryTab').onclick=()=>renderMenu('inventory');$('#artTab').onclick=()=>renderMenu('art');$('#saveBtn').onclick=()=>{saveGame(state);toast('已存檔')};$('#closeMenu').onclick=()=>$('#menuOverlay').classList.remove('on');$('#closeShop').onclick=()=>$('#shopOverlay').classList.remove('on');$('#endingSave').onclick=()=>{saveGame(state);toast('通關進度已保存')};$('#endingClose').onclick=()=>{$('#endingOverlay').classList.remove('on');enterMap('overworld',18,8)};$$('[data-dir]').forEach(b=>b.onclick=()=>{if(!state)return;const d=b.dataset.dir;const moved=world.move(d==='l'?-1:d==='r'?1:0,d==='u'?-1:d==='d'?1:0);if(moved){audio.sfx('move');refreshHUD()}});$$('[data-cmd]').forEach(b=>b.onclick=()=>battle?.command(b.dataset.cmd));
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
