import {ITEMS,SHOP_STOCK,FORMATIONS} from '../data.js';
import {MAPS,isWorld,isCamp,chapterNumber,musicForMap,nextObjective,THIRD_KINDS,FOURTH_KINDS,FIFTH_KINDS,retreatCamp} from './chapter-five.js?v=12.5';
import {preload,portrait,asset,sheet} from './assets.js';
import {Timeline} from './timeline.js?v=12.4';
import {GoldenBattle} from './battle.js?v=12.4';
import {BattleRendererV12} from './renderer.js?v=12.5';
import {AudioV12} from './audio.js?v=12.5';
import {WorldRendererV12,loadWorldArt} from './world-renderer.js?v=12.5';
import {newCampaign,normalizeCampaign,readSave,writeSave,LEGACY_KEY,CHAPTERS,OBJECTIVES,tile,walkable,route,battleState,storeCheckpoint,resolveEncounter,buyItem,equipItem,useItem,beginChapterTwo,provisionConvoy,beginChapterThree,agreeAlliance,beginChapterFour,orderSupplyEscort,beginChapterFive,orderFortDefense} from './campaign-state.js?v=12.5';
import {effective} from './rules.js?v=12.4';

const $=s=>document.querySelector(s),audio=new AudioV12();
const FIFTH_BATTLES={
 fortPatrol:{title:'北岸遭遇',banner:'魏軍巡邏',result:'巡兵已退',detail:'巡邏已退，接應進度與軍勢保留。'},
 signalDefense:{title:'烽火接應',banner:'保全烽火臺',result:'烽火已傳',detail:'烽火旗號已傳回江陵，兩路準備進度已保存。'},
 convoyDefense:{title:'北岸護糧',banner:'保全北岸糧隊',result:'糧車已達',detail:'糧隊平安抵達，另得軍糧 × 2，獎勵只發放一次。'},
 jianglingSiege:{title:'江陵守望',banner:'烽火 · 糧道齊備',result:'江陵已守',detail:'曹仁、徐晃與張郃已退，諸軍返回安民軍府。'}
};
let state=null,images,world,battle,renderer,timeline,battleKind=null,dialogue=null,dialogueDone=null,dialogueIndex=0,itemSelection=null,campTab='party',path=[],pathTimer=null,holdTimer=null,worldRAF,lastDraw=0,saveFailed=false;
const delta={u:[0,-1],d:[0,1],l:[-1,0],r:[1,0]};
function say(text){$('#worldMessage').textContent=text;}
function hasOverlay(){return [...document.querySelectorAll('.campaign-overlay')].some(e=>!e.hidden);}
function free(){return state&&!$('#worldScene').hidden&&$('#battle').hidden&&!hasOverlay();}
function stopPath(){path=[];clearTimeout(pathTimer);clearInterval(holdTimer);}
function save({backup=false}={}){if(!state)return false;const ok=writeSave(localStorage,state,{backup});$('#saveLabel').textContent=ok?'進度已保存':'無法寫入存檔';if(!ok&&!saveFailed){say('此瀏覽器無法保存進度。請確認未限制網站儲存空間。');saveFailed=true;}return ok;}
function audioUI(){const ok=audio.isReady()&&!audio.muted;for(const id of ['sound','worldSound']){$('#'+id).textContent=ok?'聲音 ✓':'聲音';$('#'+id).setAttribute('aria-pressed',String(ok));$('#'+id).setAttribute('aria-label',ok?'關閉聲音':'開啟聲音');}}
function enableAudio(mode){audio.start(mode);void audio.enable().then(audioUI);}
function toggleSound(){if(audio.isReady()&&!audio.muted)audio.mute();else void audio.enable().then(audioUI);audioUI();}
for(const id of ['sound','worldSound'])$('#'+id).onclick=toggleSound;
function refresh(){if(!state)return;$('#placeName').textContent=MAPS[state.map].name;$('#worldGold').textContent=`金 ${state.gold.toLocaleString()}`;$('#chapterLabel').textContent=`第${'一二三四五'[chapterNumber(state)-1]}章 · ${CHAPTERS[state.story.stage]}`;$('#objective').textContent=OBJECTIVES[state.story.stage];$('#dangerLabel').textContent=isWorld(state.map)?(state.encounter.safeSteps>0?'敵情暫緩':state.encounter.since>=6?'敵影逼近':state.story.stage>=20?'留意北岸巡兵':state.story.stage>=15?'留意荊南巡兵':'留意魏軍巡邏'):'此地安全';$('#waypoint').textContent=[4,9,14,19].includes(state.story.stage)?'續章':'路標';$('#waypoint').setAttribute('aria-label',state.story.stage===4?'前往第二章':state.story.stage===9?'前往第三章':state.story.stage===14?'前往第四章':state.story.stage===19?'前往第五章':'前往任務路標');audioUI();world?.draw(performance.now());}
function showWorld(message=''){stopPath();$('#campaign').hidden=false;$('#titleScene').hidden=true;$('#worldScene').hidden=false;$('#battle').hidden=true;$('#result').hidden=true;renderer?.dispose();timeline?.dispose();renderer=null;timeline=null;battle=null;battleKind=null;world=new WorldRendererV12($('#worldMap'),images,state);audio.start(musicForMap(state));refresh();if(message)say(message);save();}
function openDialogue(lines,onDone=()=>{}){stopPath();dialogue=lines;dialogueIndex=0;dialogueDone=onDone;$('#storyDialog').hidden=false;renderDialogue();$('#advanceDialog').focus();audio.sfx('ui');}
function renderDialogue(){const line=dialogue[dialogueIndex];$('#storyPortrait').src=portrait(line.hero||'liubei');$('#storyPortrait').alt=`${line.name}肖像`;$('#speakerName').textContent=line.name;$('#storyKicker').textContent=line.kicker||`第${'一二三四五'[chapterNumber(state)-1]}章 · 軍議`;$('#storyText').textContent=line.text;$('#advanceDialog').textContent=dialogueIndex===dialogue.length-1?'啟程':'繼續';}
$('#advanceDialog').onclick=()=>{audio.sfx('ui');if(++dialogueIndex<dialogue.length)renderDialogue();else{const done=dialogueDone;dialogue=null;dialogueDone=null;$('#storyDialog').hidden=true;done?.();refresh();}};
function beginNew(){state=newCampaign();save({backup:true});enableAudio('town');showWorld();openDialogue([
 {name:'劉備',hero:'liubei',kicker:'建安十二年 · 新野',text:'曹操兵鋒日盛，新野孤城難以久守。聽聞隆中有位臥龍先生，胸懷天下。'},
 {name:'趙雲',hero:'zhaoyun',text:'主公，我等護送您前往隆中。從南門出城，沿山道向東北行。'}
 ],()=>say('前往南門。可用方向鈕移動，或按「路標」沿任務路線前進。'));}
$('#startNew').onclick=()=>{if(readSave(localStorage)){$('#newDialog').hidden=false;$('#confirmNew').focus();}else beginNew();};
$('#confirmNew').onclick=()=>{$('#newDialog').hidden=true;beginNew();};$('#cancelNew').onclick=()=>{$('#newDialog').hidden=true;$('#loadJourney').focus();};
$('#loadJourney').onclick=()=>{state=readSave(localStorage);if(!state){$('#titleStatus').textContent='沒有可讀取的進度。';return;}const pending=state.pending?.kind;enableAudio(pending?battleMusic(pending):musicForMap(state));showWorld(`已回到${MAPS[state.map].name}。${OBJECTIVES[state.story.stage]}`);if(pending)startBattle(pending,true);};
$('#importLegacy').onclick=()=>{try{state=normalizeCampaign(JSON.parse(localStorage.getItem(LEGACY_KEY)));if(!state)throw Error();save({backup:true});enableAudio('town');showWorld('已接續舊版第一章進度。舊版存檔仍保留。');}catch{$('#titleStatus').textContent='舊版進度無法讀取。';}};
function enterMap(id,x,y){state.map=id;const m=MAPS[id];state.x=x??m.start.x;state.y=y??m.start.y;state.encounter.safeSteps=Math.max(3,state.encounter.safeSteps);world=new WorldRendererV12($('#worldMap'),images,state);audio.start(musicForMap(state));refresh();save();
 if(id==='xinye'&&state.story.stage===1){Object.assign(state.story,{stage:2,returned:true});save();openDialogue([{name:'孔明',hero:'kongming',kicker:'新野 · 誘敵之策',text:'博望坡兩側林木茂密，坡道狹長。待魏軍追入，便以火攻斷其前後。'}, {name:'關羽',hero:'guanyu',text:'軍需所已備好兵器與軍糧。整備完畢，便往東方迎敵。'}],()=>say('軍需所與客棧在城北。整備後前往博望坡。'));}
 else say(state.story.stage>=5?`來到${m.name}。${OBJECTIVES[state.story.stage]}`:`來到${m.name}。${id==='overworld'?'點路標可沿主線前進，途中可能遭遇巡邏。':id==='longzhong'?'靠近孔明，按「交談／調查」。':id==='bowang'?'沿坡道向北，留意敵軍先鋒。':'客棧可恢復兵力與策略。'}`);
}
function move(dir){if(!free())return false;const [dx,dy]=delta[dir]||[0,0],nx=state.x+dx,ny=state.y+dy,m=MAPS[state.map];if(!walkable(tile(state,nx,ny))||m.npcs?.some(n=>n.x===nx&&n.y===ny)){if(!path.length)say('前方有障礙。靠近人物或建築後，可按交談／調查。');return false;}state.x=nx;state.y=ny;state.steps++;if(dx)world.facing=dx;refresh();save();
 const exit=state.map==='jiangling'&&state.story.stage>=15?{...m.exit,to:'jingworld',toX:5,toY:11}:state.map==='jiangxia'&&state.story.stage>=10?{...m.exit,to:'riverworld',toX:4,toY:12}:m.exit;
 if(exit&&nx===exit.x&&ny===exit.y){stopPath();enterMap(exit.to,exit.toX,exit.toY);return true;}
 if(isWorld(state.map)){
  const p=m.points?.[tile(state)];if(p){stopPath();if(p.to==='bowang'&&state.story.stage<2){say('請先拜訪孔明並返回新野商議。');return true;}if((p.to==='changban'&&state.story.stage<6)||(p.to==='ferry'&&state.story.stage<7)){say('請先完成百姓集結與兩路救援，再向渡口前進。');return true;}if(['beaconpost','convoypost'].includes(p.to)&&state.story.stage<21){say('請先在江陵回防營地與孔明商議接應軍令。');return true;}if(p.to==='jianglinggate'&&state.story.stage<22){say('烽火與糧道準備尚未齊備，請先完成兩路接應。');return true;}if(['windaltar','shipyard'].includes(p.to)&&state.story.stage<11){say('請先在江東水寨與周瑜商議盟約。');return true;}if(p.to==='redcliffs'&&state.story.stage<12){say('東風與火船準備尚未齊備，請先完成兩路任務。');return true;}if(p.to==='grainpost'&&state.story.stage<16){say('請先在江陵營地與孔明商議護糧軍令。');return true;}if(p.to==='changshagate'&&state.story.stage<17){say('糧隊尚未抵達，請先完成桂陽護糧。');return true;}if(p.to==='changshatown'&&state.story.stage<19){say('長沙尚未安定，請先在城門與黃忠交涉。');return true;}enterMap(p.to);return true;}
  if(state.encounter.safeSteps>0)state.encounter.safeSteps--;else{state.encounter.since++;if(state.encounter.since>=10||(state.encounter.since>=4&&Math.random()<.10)){state.encounter.total++;state.encounter.since=0;stopPath();startBattle(state.story.stage>=20?'fortPatrol':state.story.stage>=15?'jingPatrol':state.story.stage>=10?'navalPatrol':state.story.stage>=5?'pursuit':'patrol');return true;}}
 }
 if(state.map==='bowang'&&state.story.stage===2&&ny<=6){stopPath();openDialogue([{name:'趙雲',hero:'zhaoyun',kicker:'博望坡 · 魏軍先鋒',text:'前方先鋒已至！請主公下令，我等先挫其銳氣。'}],()=>startBattle('vanguard'));}
 else if(state.map==='bowang'&&state.story.stage===3&&ny<=2){stopPath();openDialogue([{name:'孔明',hero:'kongming',kicker:'博望坡 · 決戰',text:'曹仁、張郃與夏侯惇主力已入坡道。此時不破，更待何時！'}],()=>startBattle('boss'));}
 refresh();save();return true;
}
function nearbyNpc(){return MAPS[state.map].npcs?.find(n=>Math.abs(n.x-state.x)+Math.abs(n.y-state.y)<=1);}
function nearBuilding(chars){for(const [dx,dy] of [[0,0],[0,-1],[0,1],[-1,0],[1,0]])if(chars.includes(tile(state,state.x+dx,state.y+dy)))return true;return false;}
function interact(){if(!free())return;stopPath();
 if(isCamp(state.map)&&nearBuilding('S')){if(state.story.stage<2){say('軍需尚在籌措。請先拜訪孔明，再返回新野。');return;}openShop();return;}
 if(isCamp(state.map)&&nearBuilding('I')){state.party.forEach(p=>{p.hp=p.maxHp;p.sp=p.maxSp;});audio.sfx('heal');save();refresh();say('客棧整軍完畢。全隊兵力與策略已恢復。');return;}
 const n=nearbyNpc();if(n){if(fifthInteraction(n)||fourthInteraction(n)||thirdInteraction(n)||chapterInteraction(n))return;if(n.id==='kongmingNpc'&&state.story.stage===0){openDialogue([
 {name:'孔明',hero:'kongming',kicker:'隆中 · 臥龍',text:'曹操雖強，荊益仍可為基業。主公若以仁義聚眾，自有可為之時。'},
 {name:'劉備',hero:'liubei',text:'備願聽先生教誨。眼下曹軍南下，新野百姓危在旦夕。'},
 {name:'孔明',hero:'kongming',text:'先回新野整軍，我自會同行。博望坡，可作第一戰。'}
 ],()=>{Object.assign(state.story,{stage:1,longzhong:true});state.party.forEach(p=>{p.hp=p.maxHp;p.sp=p.maxSp;});save();refresh();say('孔明已定迎敵之策。離開隆中，返回新野。');});}else{audio.sfx('ui');say(`${n.name}：${n.dialog.join(' ')}`);}return;}
 say('四處看看。靠近帶有「！」的人物交談，或在建築入口調查。');audio.sfx('ui');}
$('#interact').onclick=interact;
function objectivePoint(){if(state.story.stage>=5)return nextObjective(state);const m=MAPS[state.map];if(isWorld(state.map)){const ch=state.story.stage===0?'L':state.story.stage===1||state.story.stage===4?'X':'B';for(let y=0;y<m.height;y++){const x=m.rows[y].indexOf(ch);if(x>=0)return {x,y};}}
 if(state.map==='longzhong'&&state.story.stage===0)return {x:6,y:5};if(state.map==='bowang'&&state.story.stage<4)return {x:8,y:state.story.stage===2?6:2};return m.exit?{x:m.exit.x,y:m.exit.y}:null;}
function follow(goal){if(!free()||!goal)return;stopPath();const next=route(state,goal);if(!next){say('此處無法抵達，請選擇道路或空地。');return;}if(!next.length){if(nearbyNpc())interact();else say('已抵達路標。');return;}path=next;say('沿路前進中。按任一方向可停止。');const tick=()=>{if(!free()||!path.length)return;const dir=path.shift();if(!move(dir)){stopPath();return;}if(path.length)pathTimer=setTimeout(tick,150);else if(free()&&nearbyNpc())say('已抵達。按「交談／調查」交談。');};tick();}
$('#waypoint').onclick=()=>state.story.stage===4?enterChapterTwo():state.story.stage===9?enterChapterThree():state.story.stage===14?enterChapterFour():state.story.stage===19?enterChapterFive():follow(objectivePoint());$('#worldMap').onclick=e=>follow(world?.cellAt(e.clientX,e.clientY));
document.querySelectorAll('[data-dir]').forEach(button=>{button.onpointerdown=e=>{e.preventDefault();button.setPointerCapture?.(e.pointerId);stopPath();move(button.dataset.dir);holdTimer=setInterval(()=>move(button.dataset.dir),160);};button.onpointerup=button.onpointercancel=()=>{clearInterval(holdTimer);};button.onclick=e=>{if(e.detail===0){stopPath();move(button.dataset.dir);}};});
function startBattle(kind,resume=false){stopPath();battleKind=kind;$('#stage').dataset.battlefield=kind;const initial=battleState(state,kind);if(!resume){state.pending={kind,snapshot:null};storeCheckpoint(state,kind,initial);}save();$('#campaign').hidden=true;$('#battle').hidden=false;$('#battle').setAttribute('aria-label',MAPS[state.map].name+'戰鬥');$('#result').hidden=true;$('#battle').classList.remove('identity-test');$('#identity').textContent='隱名';$('#identity').setAttribute('aria-pressed','false');$('#units').replaceChildren();timeline=new Timeline();audio.start(battleMusic(kind));$('#stage').style.backgroundImage=`url('${asset(FIFTH_KINDS.includes(kind)?'backgrounds/jiangling.png':kind==='changsha'?'backgrounds/changsha.png':kind==='bridge'?'backgrounds/changban.png':['redcliff','fireships'].includes(kind)?'backgrounds/redcliff.png':'backgrounds/bowang.png')}')`;$('#stage').style.backgroundSize=kind==='changsha'?'auto 110%':kind==='bridge'?'auto 130%':['redcliff','fireships'].includes(kind)?'auto 110%':'cover';$('#stage').style.backgroundPosition=FIFTH_KINDS.includes(kind)?'center bottom':kind==='changsha'||kind==='bridge'||['redcliff','fireships'].includes(kind)?'center bottom':'center';$('#stage .enemy-banner').textContent=FIFTH_BATTLES[kind]?.banner|| (kind==='changsha'?'長沙守軍':kind==='supplyEscort'?'保全糧隊':kind==='jingPatrol'?'荊南巡兵':kind==='bridge'?'守住四回合':kind==='redcliff'?'東風 · 火船齊備':'魏軍迎擊');$('#result .eyebrow').textContent=kind==='bridge'?'長坂守橋':MAPS[state.map].name;
 battle=new GoldenBattle({timeline,audio,initialState:initial,onChange:s=>{renderer?.render(s);if(s.phase==='command'){storeCheckpoint(state,kind,s);save();}},onMessage:text=>{if(!$('#battle').classList.contains('identity-test'))$('#message').textContent=text;},onFinish:(result,s)=>{resolveEncounter(state,kind,s,result.win);save();$('#resultTitle').textContent=result.win?(FIFTH_BATTLES[kind]?.result|| (kind==='changsha'?'長沙已安':kind==='supplyEscort'?'糧隊已達':kind==='redcliff'?'赤壁大捷':kind==='windward'?'風旗已定':kind==='fireships'?'火船備妥':kind==='bridge'?'護民渡河':kind==='boss'?'博望大捷':kind.startsWith('rescue')?'接應成功':'擊退魏軍')):(state.story.stage>=5?'退守營地':'退守新野');$('#resultDetails').textContent=result.win?`獲得 ${result.gold} 金 · ${result.exp} 經驗${result.levelUps.length?'\n'+[...new Set(result.levelUps)].join('、')+' 升級！':''}\n${FIFTH_BATTLES[kind]?.detail|| (kind==='changsha'?'黃忠已見安民之誠，諸軍返回長沙軍府。':kind==='supplyEscort'?'糧道已保全，另得軍糧 × 2；前往長沙城門交涉。':kind==='redcliff'?'連環艦已破，聯軍平安返回江陵。':kind==='windward'?'魏軍哨騎已退，東風旗號準備完成。':kind==='fireships'?'火船與引火物已保全，靜候決戰軍令。':kind==='bridge'?'守橋四回合完成，百姓已平安抵達江夏。':kind==='boss'?'第一章 · 博望首戰告捷。':kind.startsWith('rescue')?'此路百姓已接應，救援進度已保存。' :'整軍再行，保留目前兵力與策略。')}`:`全軍退守${MAPS[state.map].name}，損失 120 金。兵力恢復至六成五，可到客棧整軍。`;if(FIFTH_KINDS.includes(kind))$('#message').textContent=result.win?'江陵接應告捷，旗號與獎勵已保存。':'退守回防營地，整軍再戰。';else if(FOURTH_KINDS.includes(kind))$('#message').textContent=result.win?'此戰告捷，護糧與獎勵已保存。':'退守江陵，整軍再戰。';else if(THIRD_KINDS.includes(kind))$('#message').textContent=result.win?'此戰告捷，準備與獎勵已保存。':'退守水寨，整軍再戰。';}});
 renderer=new BattleRendererV12($('#battle'),images,timeline,battle);battle.say(`${battle.actor().name}，請下令。`);$('#battle h1').firstChild.textContent=FIFTH_BATTLES[kind]?.title|| (kind==='changsha'?'弓將決戰':kind==='supplyEscort'?'桂陽護糧':kind==='jingPatrol'?'荊南遭遇':kind==='redcliff'?'赤壁破陣':kind==='windward'?'東風布陣':kind==='fireships'?'火船護航':kind==='navalPatrol'?'江岸遭遇':kind==='bridge'?'長坂守橋':kind==='boss'?'博望之戰':kind==='vanguard'?'破陣迎敵':kind.startsWith('rescue')?'長坂救援':'山道遭遇');$('#battle h1 small').textContent=kind==='jianglingSiege'?'烽糧接應 · 城門決戰':kind==='changsha'?'荊南定策 · 護糧安民':kind==='redcliff'?'連環艦決戰 · 擊破魏軍':kind==='bridge'?'護民渡河 · 堅守四回合':kind==='boss'?'三國戰策 · 孔明篇':MAPS[state.map].name;$('#commands button').focus();}
document.querySelectorAll('[data-cmd]').forEach(button=>button.onclick=()=>battle?.command(button.dataset.cmd));$('#cancel').onclick=()=>battle?.cancel();$('#identity').onclick=()=>{if(!battle)return;const active=$('#battle').classList.toggle('identity-test');$('#identity').textContent=active?'顯名':'隱名';$('#identity').setAttribute('aria-pressed',String(active));renderer.render(battle.state);};
$('#replay').onclick=()=>{if(!battle?.state.result)return;const won=battle.state.result.win,kind=battleKind;showWorld(won?'此戰告捷。軍勢與獎勵已保存。':'已退回營地。請先在客棧休整，再行出征。');if(won&&kind==='jianglingSiege')openDialogue([{name:'徐晃',hero:'xuhuang',kicker:'第五章 · 魏軍撤退',text:'旗號相連，糧道未斷。今日難破此城，諸軍隨我撤回北岸！'},{name:'孔明',hero:'kongming',kicker:'江陵 · 安民軍府',text:'城池可守，靠的是烽火互援、糧道不絕與諸將同心。先安置傷兵，再將口糧送到百姓手中。'},{name:'劉備',hero:'liubei',text:'五章旅程至此告一段落。江陵軍府常備醫者與軍需，諸位可在此休整。'}],()=>say('第五章完成，進度已保存。可在江陵軍府整軍與探索。'));else if(won&&kind==='changsha')openDialogue([{name:'黃忠',hero:'huangzhong',kicker:'第四章 · 長沙安民',text:'老夫守的是一城百姓。諸位保全糧道，又不棄傷者，這份誠意勝過千言萬語。'},{name:'劉備',hero:'liubei',kicker:'長沙 · 同心',text:'城門既開，軍糧先送百姓，傷兵先受醫治。天下雖未定，此地不必再受兵火。'}],()=>say('第四章完成，進度已保存。點「續章」前往江陵守望。'));else if(won&&kind==='redcliff')openDialogue([{name:'周瑜',hero:'zhouyu',kicker:'第三章 · 赤壁大捷',text:'火船順風而至，連環艦已破。今日之勝，賴兩軍同心，諸將奮勇。'},{name:'孔明',hero:'kongming',kicker:'江陵 · 三章旅程',text:'博望守土、長坂護民、赤壁破敵。每一步，都有百姓與同袍相伴。\n\n先在江陵安定軍民，來日再議天下。'}],()=>say('第三章完成，進度已保存。點「續章」可前往荊南定策。'));else if(won&&kind==='bridge')openDialogue([{name:'張飛',hero:'zhangfei',kicker:'第二章 · 長坂護民',text:'渡船都過去了！追兵一時上不了橋，咱們也該撤了。'},{name:'孔明',hero:'kongming',kicker:'江夏 · 安民',text:'兩路百姓平安渡河，糧車與傷者皆已安置。\n\n先在江夏整軍，這一路的同心與勇氣，我們都記下了。'}],()=>say('第二章完成，進度已保存。點「續章」可前往赤壁風起。'));else if(won&&kind==='boss')openDialogue([{name:'孔明',hero:'kongming',kicker:'第一章 · 博望首戰告捷',text:'曹軍鋒芒已挫，新野百姓得以安歇。\n\n首戰之勝，靠的是五將同心。天下未定，我們的旅程才剛開始。'}],()=>say('第一章完成，通關進度已保存。點「續章」可前往長坂護民。'));};
function openCamp(tab='party'){if(!free())return;stopPath();campTab=tab;$('#campDialog').hidden=false;renderCamp();$('#closeCamp').focus();audio.sfx('ui');}
$('#openCamp').onclick=()=>openCamp();$('#closeCamp').onclick=()=>{$('#campDialog').hidden=true;$('#openCamp').focus();};document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{campTab=b.dataset.tab;renderCamp();});
function node(tag,text,className=''){const e=document.createElement(tag);if(text!=null)e.textContent=text;if(className)e.className=className;return e;}
function renderCamp(){const body=$('#campBody');body.replaceChildren();$('#campNotice').textContent=`金 ${state.gold} · ${state.formation}陣 · 進度自動保存`;document.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.tab===campTab)));
 if(campTab==='party'){for(const p of state.party){const row=node('div',null,'party-row'),im=node('img');im.src=portrait(p.id);im.alt=p.name;row.append(im);const copy=node('div');copy.append(node('h3',`${p.name} · ${p.role}`),node('p',`Lv.${p.level}　兵 ${p.hp}/${p.maxHp}　策 ${p.sp}/${p.maxSp}`),node('p',`${ITEMS[p.weapon].name} ／ ${ITEMS[p.armor].name}`),node('p',`武 ${effective(p).atk}　防 ${effective(p).def}　智 ${effective(p).int}　速 ${effective(p).agi}`));row.append(copy);body.append(row);}}
 else if(campTab==='inventory'){const items=Object.entries(state.inventory).filter(([,count])=>count>0);if(!items.length)body.append(node('p','尚無可用物品。','journal-copy'));for(const [id,count] of items){const it=ITEMS[id],row=node('div',null,'item-row'),copy=node('div');copy.append(node('strong',`${it.name} × ${count}`),node('p',it.desc));const button=node('button',it.type==='consumable'?'使用':'配給');button.onclick=()=>chooseHero(id);row.append(copy,button);body.append(row);}}
 else if(campTab==='formation'){for(const [name,formation] of Object.entries(FORMATIONS)){const button=node('button',null,'formation-choice');button.append(node('span',name+'陣'),node('small',formation.desc));button.setAttribute('aria-pressed',String(name===state.formation));button.onclick=()=>{state.formation=name;audio.sfx('ui');save();refresh();renderCamp();};body.append(button);}}
 else {const copy=node('div',null,'journal-copy');copy.append(node('h3',CHAPTERS[state.story.stage]),node('p',OBJECTIVES[state.story.stage]),node('p',state.story.stage>=20?'江陵回防營地可整軍。烽火臺與北岸糧道可任選先後，接應後前往城門。烽火聯防使決戰敵軍攻擊降低，糧隊另外提供兩份軍糧。':state.story.stage>=15?'江陵軍議後接應桂陽糧隊，再前往長沙交涉。軍需所與醫者可補給，軍議可退回本章營地。':state.story.stage>=10?'江東水寨可整軍。完成東風與火船兩路準備後，前往赤壁登船口會合；軍糧、策略與裝備皆會影響決戰。':state.story.stage>=5?'長坂古道的兩路百姓需分別接應。南撤營地有軍需所與客棧，救援後前往當陽渡口守橋。':'新野南門通往荊州北境。隆中在東北，博望坡在東方。城北軍需所可購買裝備，客棧可恢復兵力與策略。'));body.append(copy);if(state.story.stage===4){const next=node('button','前往第二章 · 長坂護民','journal-action');next.onclick=()=>{$('#campDialog').hidden=true;enterChapterTwo();};body.append(next);}if(state.story.stage===9){const next=node('button','前往第三章 · 赤壁風起','journal-action');next.onclick=()=>{$('#campDialog').hidden=true;enterChapterThree();};body.append(next);}if(state.story.stage===14){const next=node('button','前往第四章 · 荊南定策','journal-action');next.onclick=()=>{$('#campDialog').hidden=true;enterChapterFour();};body.append(next);}if(state.story.stage===19){const next=node('button','前往第五章 · 江陵守望','journal-action');next.onclick=()=>{$('#campDialog').hidden=true;enterChapterFive();};body.append(next);}const hub=retreatCamp(state);const back=node('button',`返回${MAPS[hub].name}休整`,'journal-action');back.onclick=()=>{$('#campDialog').hidden=true;enterMap(hub);say('已返回營地，劇情與裝備進度保留。');};const title=node('button','保存並返回標題','journal-action');title.onclick=()=>{save();stopPath();$('#campDialog').hidden=true;$('#worldScene').hidden=true;$('#titleScene').hidden=false;refreshTitle();audio.stop();};body.append(back,title);}}
function chooseHero(id){itemSelection=id;$('#itemTitle').textContent=`${ITEMS[id].name} · 選擇武將`;$('#itemTargets').replaceChildren();for(const p of state.party){const it=ITEMS[id],button=node('button',null,'target-hero');button.append(node('span',p.name),node('small',it.type==='consumable'?`兵 ${p.hp}/${p.maxHp} · 策 ${p.sp}/${p.maxSp}`:`目前：${ITEMS[p[it.type]].name}`));if(it.type==='consumable')button.disabled=it.heal?p.hp>=p.maxHp:p.sp>=p.maxSp;button.onclick=()=>{const ok=it.type==='consumable'?useItem(state,id,p.id):equipItem(state,p.id,id);if(ok){audio.sfx(it.type==='consumable'?'heal':'ui');save();refresh();$('#itemDialog').hidden=true;renderCamp();$('#campNotice').textContent=`${p.name} ${it.type==='consumable'?'使用':'配備'}了${it.name}。`;}};$('#itemTargets').append(button);}$('#itemDialog').hidden=false;$('#closeItem').focus();}
$('#closeItem').onclick=()=>{$('#itemDialog').hidden=true;itemSelection=null;};
function openShop(){$('#shopDialog small').textContent=MAPS[state.map].name+' · 軍需所';$('#shopDialog').hidden=false;renderShop();$('#closeShop').focus();audio.sfx('ui');}
function renderShop(){const body=$('#shopBody');body.replaceChildren();$('#shopGold').textContent=`持有金錢：${state.gold.toLocaleString()} 金`;for(const id of SHOP_STOCK){const it=ITEMS[id],row=node('div',null,'shop-row'),copy=node('div');copy.append(node('strong',it.name),node('p',`${it.desc}　持有 ${state.inventory[id]||0}`));const button=node('button',`${it.price} 金`);button.disabled=state.gold<it.price;button.onclick=()=>{const error=buyItem(state,id);$('#shopNotice').textContent=error||`已購入${it.name}。${it.type==='consumable'?'可在軍勢選單使用。':'請在軍勢 → 物品中配給武將。'}`;if(!error){audio.sfx('ui');save();refresh();renderShop();}};row.append(copy,button);body.append(row);}}
$('#closeShop').onclick=()=>{$('#shopDialog').hidden=true;};$('#saveJourney').onclick=()=>{if(save())say('目前旅程已保存。重新開啟遊戲可選擇「繼續旅程」。');audio.sfx('ui');};
addEventListener('keydown',e=>{if(e.altKey||e.ctrlKey||e.metaKey||['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName))return;const dirs={ArrowUp:'u',w:'u',ArrowDown:'d',s:'d',ArrowLeft:'l',a:'l',ArrowRight:'r',d:'r'};if(free()&&dirs[e.key]){e.preventDefault();stopPath();move(dirs[e.key]);}else if(e.key==='Enter'&&!e.repeat&&free()){e.preventDefault();interact();}else if(e.key==='Escape'){e.preventDefault();if(!$('#itemDialog').hidden)$('#itemDialog').hidden=true;else if(!$('#shopDialog').hidden)$('#shopDialog').hidden=true;else if(!$('#campDialog').hidden)$('#campDialog').hidden=true;else if(battle)battle.cancel();else if(free())openCamp();}});
document.addEventListener('visibilitychange',()=>{stopPath();audioUI();if(!document.hidden&&audio.hasEntered&&!audio.muted)audio.unlock(false,false).then(audioUI);});addEventListener('pageshow',audioUI);
document.addEventListener('v12audioerror',()=>{say('音樂載入失敗，請點「聲音」重試。');});
function frame(now){if(!document.hidden&&free()&&now-lastDraw>180){world?.draw(now);lastDraw=now;}worldRAF=requestAnimationFrame(frame);}
function refreshTitle(){$('#loadJourney').disabled=!readSave(localStorage);try{$('#importLegacy').hidden=!localStorage.getItem(LEGACY_KEY)||!!readSave(localStorage);}catch{$('#importLegacy').hidden=true;}$('#titleStatus').textContent=readSave(localStorage)?'自動存檔已備妥，可繼續旅程。':'方向鈕探索 · 交談推進 · 隨時保存';}
try{const [battleArt,mapArt,chapterArt]=await Promise.all([preload((n,total)=>$('#titleStatus').textContent=`整軍備戰 ${n} / ${total}`),loadWorldArt(),loadChapterArt()]);images=new Map([...battleArt,...mapArt,...chapterArt]);$('#startNew').disabled=false;refreshTitle();worldRAF=requestAnimationFrame(frame);
 if(new URLSearchParams(location.search).has('qa'))window.__Campaign={get state(){return state;},get audio(){return audio;},get battle(){return battle;},get timeline(){return timeline;},get renderer(){return renderer;},move,interact,startBattle,save,route,enterMap};
}catch(error){$('#titleStatus').textContent=`${error.message}，請重新載入。`;console.error(error);}

function battleMusic(kind){return FIFTH_KINDS.includes(kind)?'fortress':kind==='changsha'?'jingnan':['redcliff','fireships'].includes(kind)?'naval':kind==='bridge'?'bridge':kind==='boss'?'boss':'battle';}
async function loadChapterArt(){const urls=[sheet('caochun'),portrait('caochun'),asset('backgrounds/changban.png'),sheet('xuhuang'),portrait('xuhuang'),portrait('zhouyu'),asset('backgrounds/redcliff.png'),sheet('huangzhong'),portrait('huangzhong'),asset('backgrounds/changsha.png'),asset('backgrounds/changsha-wide.png'),asset('backgrounds/jiangling.png')];return new Map(await Promise.all(urls.map(url=>new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve([url,im]);im.onerror=()=>reject(Error('章節素材載入失敗'));im.src=url;}))));}
function enterChapterTwo(){if(!beginChapterTwo(state))return;save();showWorld();openDialogue([{name:'劉備',hero:'liubei',kicker:'第二章 · 長坂護民',text:'新野已不可久守。百姓願隨我們南下，備不能棄他們於兵火。'},{name:'孔明',hero:'kongming',text:'先到南撤營地發放軍糧，再接應長坂古道上掉隊的兩路百姓。當陽渡船已在等候。'}],()=>say(OBJECTIVES[state.story.stage]));}
function chapterInteraction(n){
 if(n.id==='kongmingNpc'&&state.map==='jiangxia'&&state.story.stage>=9){say('孔明：'+OBJECTIVES[state.story.stage]);return true;}
 if(n.id==='elder'&&state.story.stage>=6){say('軍糧已發放。'+OBJECTIVES[state.story.stage]);return true;}
 if(n.id==='ferrymaster'&&state.story.stage>=9){say('百姓已平安抵達江夏，渡船也已泊妥。');return true;}
 if(n.id==='innkeeper'){state.party.forEach(p=>{p.hp=p.maxHp;p.sp=p.maxSp;});audio.sfx('heal');save();refresh();say('傷兵已安置。全隊兵力與策略已恢復。');return true;}
 if(n.id==='elder'&&state.story.stage===5){if(state.inventory.ration<2){say('需要兩份軍糧。可在北面的軍需所購買，再回來集結。');return true;}openDialogue([{name:'劉備',hero:'liubei',kicker:'南撤營地 · 發放軍糧',text:'先將兩份軍糧發給百姓。糧車走在前面，傷者由我等護送。'},{name:'孔明',hero:'kongming',text:'西路糧車與東路傷者落在長坂古道。接應兩路百姓後，大家在當陽渡口會合。'}],()=>{const error=provisionConvoy(state);save();refresh();say(error||OBJECTIVES[state.story.stage]);});return true;}
 if(n.rescue&&state.story.stage===6&&!state.story.rescued.includes(n.rescue)){openDialogue([{name:n.rescue==='west'?'趙雲':'關羽',hero:n.rescue==='west'?'zhaoyun':'guanyu',kicker:n.rescue==='west'?'長坂 · 西路糧車':'長坂 · 東路傷者',text:n.rescue==='west'?'追兵逼近糧車！先擊退這支魏軍，讓百姓沿古道撤往渡口。':'東路傷者尚未脫身。諸位隨我接應，守住這一段道路。'}],()=>startBattle(n.rescue==='west'?'rescueWest':'rescueEast'));return true;}
 if(n.id==='ferrymaster'&&[7,8].includes(state.story.stage)){openDialogue([{name:'孔明',hero:'kongming',kicker:'當陽渡口 · 守橋軍令',text:'兩路百姓都到了。渡船需要四回合才能撤完，務必守住橋頭。防禦與補給能減少損失，不必與追兵決死。'},{name:'曹純',hero:'caochun',kicker:'魏軍追擊',text:'橋頭就在眼前！若讓他們過河，便再難截住。'},{name:'張飛',hero:'zhangfei',text:'百姓先過橋！俺與諸位守在此處，誰也休想闖過去。'}],()=>{state.story.stage=8;save();startBattle('bridge');});return true;}
 return false;
}

function enterChapterThree(){if(!beginChapterThree(state))return;save();showWorld();openDialogue([{name:'孔明',hero:'kongming',kicker:'第三章 · 赤壁風起',text:'江夏已安，曹軍卻仍沿江而進。唯有聯結江東，才能共守這一片山河。'},{name:'劉備',hero:'liubei',text:'與周都督商議盟約吧。軍中傷者先行休整，這場水戰須同心而行。'}],()=>say(OBJECTIVES[state.story.stage]));}
function thirdInteraction(n){
 if(n.id==='zhouyu'&&state.story.stage===10){openDialogue([{name:'周瑜',hero:'zhouyu',kicker:'江東水寨 · 孫劉盟約',text:'曹軍連環艦雖多，卻不利轉向。我等備火船，先生觀風向；兵力與謀略，缺一不可。'},{name:'孔明',hero:'kongming',text:'東風祭壇與火船工坊各需一隊接應，兩路可任選先後。準備齊備後，前往赤壁登船口會合。'}],()=>{agreeAlliance(state);save();refresh();say(OBJECTIVES[state.story.stage]);});return true;}
 if(n.id==='zhouyu'){say('周瑜：'+OBJECTIVES[state.story.stage]);return true;}
 if(n.plan&&state.story.stage>=11){if(state.story.plans.includes(n.plan)){say(n.name+'：'+n.dialog.join(' '));return true;}if(state.story.stage!==11){say(OBJECTIVES[state.story.stage]);return true;}openDialogue([{name:n.plan==='wind'?'孔明':'趙雲',hero:n.plan==='wind'?'kongming':'zhaoyun',kicker:n.plan==='wind'?'東風祭壇 · 接應旗手':'火船工坊 · 保全火船',text:n.plan==='wind'?'風向已穩，卻有魏軍哨騎逼近。先擊退敵軍，再升起約定的旗號。':'工坊外的魏軍正欲截斷火船。守住泊位，讓造船師將油罐與蘆葦運上船！'}],()=>startBattle(n.plan==='wind'?'windward':'fireships'));return true;}
 if(n.id==='zhouyuBattle'&&[12,13].includes(state.story.stage)){openDialogue([{name:'周瑜',hero:'zhouyu',kicker:'赤壁 · 決戰軍令',text:'東風與火船都已備妥。火船先行，可削去魏軍兩成兵力；諸將登上連環艦，擊破守軍！'},{name:'徐晃',hero:'xuhuang',kicker:'魏軍連環艦',text:'火勢雖猛，艦上尚有精兵。隨我守住甲板！'},{name:'劉備',hero:'liubei',text:'兩軍同心，五將並肩。為百姓與同袍，破此敵陣！'}],()=>{state.story.stage=13;save();startBattle('redcliff');});return true;}
 if(n.id==='zhouyuBattle'&&state.story.stage>=14){say('周瑜：赤壁之戰已勝，諸軍正在江陵休整。');return true;}
 return false;
}

function enterChapterFour(){if(!beginChapterFour(state))return;save();showWorld();openDialogue([{name:'孔明',hero:'kongming',kicker:'第四章 · 荊南定策',text:'赤壁之後，荊南百姓仍苦於糧道阻斷。要使城池安定，先讓百姓有糧可食。'},{name:'劉備',hero:'liubei',text:'先在江陵商議，再護送桂陽糧隊。長沙有一位白鬚弓將，當以誠意相見。'}],()=>say(OBJECTIVES[state.story.stage]));}
function fourthInteraction(n){
 if(state.story.stage<15)return false;
 if(n.id==='merchant'){openShop();return true;}
 if(n.id==='kongmingNpc'&&state.map==='jingcamp'){if(state.story.stage!==15){say('孔明：'+OBJECTIVES[state.story.stage]);return true;}openDialogue([{name:'孔明',hero:'kongming',kicker:'江陵 · 護糧軍令',text:'桂陽糧站遭截糧軍圍困。先接應糧官，糧隊抵達後，再往長沙城門交涉。'},{name:'趙雲',hero:'zhaoyun',text:'軍需與傷兵都已安頓。諸位可在醫者處整軍，再沿荊南古道前行。'}],()=>{orderSupplyEscort(state);save();refresh();say(OBJECTIVES[state.story.stage]);});return true;}
 if(n.id==='grainOfficer'){if(state.story.supplySecured){say('糧官：'+n.dialog.join(' '));return true;}if(state.story.stage!==16){say(OBJECTIVES[state.story.stage]);return true;}openDialogue([{name:'趙雲',hero:'zhaoyun',kicker:'桂陽 · 保全糧隊',text:'截糧軍擋住了古道。先破敵陣，再讓糧車通過；百姓的口糧不可有失。'}],()=>startBattle('supplyEscort'));return true;}
 if(n.id==='huangzhongNpc'){if(state.map==='changshatown'||state.story.stage>=19){openDialogue([{name:'黃忠',hero:'huangzhong',kicker:'長沙軍府',text:n.dialog.join(' ')}]);return true;}if(![17,18].includes(state.story.stage)){say(OBJECTIVES[state.story.stage]);return true;}openDialogue([{name:'黃忠',hero:'huangzhong',kicker:'長沙 · 白鬚弓將',text:'糧隊既已安全抵達，老夫敬諸位護民之心。只是城防重任在肩，還請諸將與我一試身手。'},{name:'關羽',hero:'guanyu',text:'黃將軍弓術不凡，我等當全力迎戰。軍糧與計策既備，便在此一決！'}],()=>{state.story.stage=18;save();startBattle('changsha');});return true;}
 return false;
}

function enterChapterFive(){if(!beginChapterFive(state))return;save();showWorld();openDialogue([{name:'孔明',hero:'kongming',kicker:'第五章 · 江陵守望',text:'荊南已定，江陵北岸卻有魏軍集結。先回防營地，接應烽火與糧道，再守城門。'},{name:'黃忠',hero:'huangzhong',text:'老夫留守長沙，護好後方糧道。諸位的兵器、軍糧與同袍，都將隨這一程帶往江陵。'}],()=>say(OBJECTIVES[state.story.stage]));}
function fifthInteraction(n){
 if(state.story.stage<20)return false;
 if(n.id==='kongmingNpc'&&['jianglingfort','forttown'].includes(state.map)){if(state.story.stage!==20){say('孔明：'+OBJECTIVES[state.story.stage]);return true;}openDialogue([{name:'孔明',hero:'kongming',kicker:'江陵 · 回防軍令',text:'烽火臺遭到哨騎逼近，糧隊也在北岸受阻。兩路可任選先後，完成後在城門會合。'},{name:'趙雲',hero:'zhaoyun',text:'烽火傳開，各營便能互相接應，使魏軍攻勢減弱；保全糧道，還能補充兩份軍糧。'}],()=>{orderFortDefense(state);save();refresh();say(OBJECTIVES[state.story.stage]);});return true;}
 if(n.defense){if(state.story.defensePlans.includes(n.defense)){say(n.name+'：'+n.dialog.join(' '));return true;}if(state.story.stage!==21){say(OBJECTIVES[state.story.stage]);return true;}openDialogue([{name:n.defense==='beacon'?'趙雲':'關羽',hero:n.defense==='beacon'?'zhaoyun':'guanyu',kicker:n.defense==='beacon'?'北岸 · 烽火接應':'北岸 · 糧道接應',text:n.defense==='beacon'?'守住烽火臺，讓約定的旗號傳回城中。敵軍哨騎不容再進！':'糧車正在古道上受阻。先擊退截糧軍，再把口糧送入江陵！'}],()=>startBattle(n.defense==='beacon'?'signalDefense':'convoyDefense'));return true;}
 if(n.id==='officer'&&state.map==='jianglinggate'){if(state.story.stage>=24){say('校尉：城門已守，軍民皆安。');return true;}if(![22,23].includes(state.story.stage)){say(OBJECTIVES[state.story.stage]);return true;}openDialogue([{name:'孔明',hero:'kongming',kicker:'江陵 · 城門軍令',text:'烽火旗號已傳，糧車已入城。各營互援，敵軍攻擊將減弱。這一戰，當守住軍民安居之地。'},{name:'徐晃',hero:'xuhuang',kicker:'魏軍 · 北岸來襲',text:'曹仁與張郃已到，諸軍向前，破開江陵城門！'},{name:'劉備',hero:'liubei',text:'五將同心，守住江陵！'}],()=>{state.story.stage=23;save();startBattle('jianglingSiege');});return true;}
 return false;
}
