import {CELL,POSES,sheet,portrait,fxAtlas,FX_NAMES} from './assets.js';
import {SKILLS,effective} from './rules.js?v=12.1';
export class BattleRendererV12{
 constructor(root,images,timeline,battle){Object.assign(this,{root,images,timeline,battle});this.canvas=root.querySelector('canvas');this.ctx=this.canvas.getContext('2d');this.stage=root.querySelector('#stage');this.unitRoot=root.querySelector('#units');this.positions=new Map();this.reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;this.build();this.observer=new ResizeObserver(()=>this.measure());this.observer.observe(this.stage);this._draw=t=>this.draw(t);timeline.listeners.add(this._draw);this.render(battle.state);this.measure();}
 build(){this.nodes=new Map();const s=this.battle.state;for(let i=0;i<5;i++)for(const [side,unit] of [['ally',s.party[i]],['enemy',s.enemies[i]]]){if(!unit)continue;const el=document.createElement('button');el.className=`unit ${side}`;el.style.gridRow=i+1;el.style.gridColumn=side==='ally'?1:2;el.dataset.id=unit.id;el.dataset.side=side;el.dataset.index=i;el.innerHTML='<div class="unit-info"><div class="unit-top"><strong class="unit-name"></strong><span class="hp-number"></span></div><span class="troopbar"><i></i></span></div>';el.querySelector('strong').textContent=unit.name;el.onclick=()=>this.battle.target(side,i);this.unitRoot.append(el);this.nodes.set(unit.id,el);}}
 measure(){const sr=this.stage.getBoundingClientRect();this.width=sr.width;this.height=sr.height;if(['fortPatrol','signalDefense','convoyDefense','jianglingSiege'].includes(this.stage.dataset.battlefield)){const coverWidth=Math.max(sr.width,sr.height*2/3);this.stage.style.backgroundSize=`${Math.ceil(coverWidth*1.12)}px auto`;}const dpr=Math.min(2,devicePixelRatio||1);this.canvas.width=Math.round(sr.width*dpr);this.canvas.height=Math.round(sr.height*dpr);this.ctx.setTransform(dpr,0,0,dpr,0,0);this.ctx.imageSmoothingEnabled=false;for(const [id,el] of this.nodes){const r=el.getBoundingClientRect();const h=Math.max(30,r.height-26);const w=h*CELL.w/CELL.h;this.positions.set(id,{x:r.left-sr.left+r.width/2-w/2,y:r.top-sr.top,w,h,center:r.left-sr.left+r.width/2,rowY:r.top-sr.top,rowH:r.height});}this.draw(this.timeline.time);}
 render(s){const identity=this.root.classList.contains('identity-test');for(const [side,units] of [['ally',s.party],['enemy',s.enemies]])units.forEach((u,i)=>{const el=this.nodes.get(u.id);el.classList.toggle('active',side==='ally'&&i===s.actor&&s.phase!=='ended');el.classList.toggle('dead',u.hp<=0);el.classList.toggle('low',u.hp/u.maxHp<.3);const target=s.phase==='target'&&s.selection?.side===side&&u.hp>0;el.classList.toggle('target',target);el.disabled=!target;el.setAttribute('aria-label',`${identity?`${side==='ally'?'我軍':'敵軍'} ${i+1}`:u.name}，兵力 ${u.hp}／${u.maxHp}${target?'，可選取':''}`);el.querySelector('.hp-number').textContent=u.hp.toLocaleString('en-US');el.querySelector('.troopbar i').style.width=`${Math.max(0,u.hp/u.maxHp)*100}%`;});
 const p=s.party[s.actor];this.root.querySelector('#round').textContent=`第 ${String(s.round).padStart(2,'0')} 回合${s.holdRounds?'／'+String(s.holdRounds).padStart(2,'0'):''}`;this.root.querySelector('#formation').textContent=`${s.formation}陣`;const image=this.root.querySelector('#portrait');if(image.dataset.id!==p.id){image.src=portrait(p.id);image.dataset.id=p.id;}image.alt=identity?'':`${p.name}獨立肖像`;image.setAttribute('aria-hidden',String(identity));
 this.root.querySelector('#actorName').textContent=p.name;this.root.querySelector('#actorStats').innerHTML=`<span>兵 ${p.hp}/${p.maxHp}</span><span><em>策 ${p.sp} / ${p.maxSp}</em></span>`;this.root.querySelector('#supply').textContent=`軍糧 × ${s.rations}`;
 const open=s.phase==='skills';this.root.querySelector('#commands').hidden=open;const skills=this.root.querySelector('#skills');skills.hidden=!open;this.root.querySelector('#cancel').hidden=!['skills','target'].includes(s.phase);this.root.querySelector('#actionLabel').textContent=s.phase==='target'?'指定目標':s.phase==='enemy'?`${s.enemyFaction||'魏軍'}行動`:s.phase==='resolving'?'軍令執行':open?'軍師計策':'選擇軍令';this.root.querySelectorAll('[data-cmd]').forEach(b=>{b.disabled=!['command','target','skills'].includes(s.phase);});
 if(open){skills.replaceChildren();for(const sk of SKILLS.filter(x=>effective(p).int>=x.minInt)){const button=document.createElement('button');button.textContent=sk.name;const cost=document.createElement('small');cost.textContent=`${sk.cost} 策略`;button.append(cost);button.disabled=p.sp<sk.cost;button.onclick=()=>this.battle.skill(sk.id);skills.append(button);}}
 this.root.querySelector('#message').textContent=this.root.classList.contains('identity-test')?`隱名辨識 · 我軍 ${s.party.length}／敵軍 ${s.enemies.length}`:this.battle.message;
 if(s.result){this.root.querySelector('#result').hidden=false;this.root.querySelector('#resultTitle').textContent=s.result.win?'博望大捷':'重整旗鼓';this.root.querySelector('#resultDetails').textContent=s.result.win?`獲得 ${s.result.gold} 金 · ${s.result.exp} 經驗\n五將同心，再定天下。`:'勝敗乃兵家常事。調整計策與陣型，再戰。';this.root.querySelector('#replay').focus();}}
 dispose(){this.observer.disconnect();this.timeline.listeners.delete(this._draw);}
 draw(time){const c=this.ctx;c.clearRect(0,0,this.width,this.height);const s=this.battle.state;for(const [side,units] of [['ally',s.party],['enemy',s.enemies]])for(let i=0;i<units.length;i++){const u=units[i],p=this.positions.get(u.id);if(!p)continue;const a=this.timeline.animations.get(u.id);const pose=a?.pose||(u.hp<=0?'ko':'idle');const col=pose==='idle'?(this.reduced?0:Math.floor((time+i*111)/720)%2):POSES[pose][0];const im=this.images.get(sheet(u.archetype||u.id));c.save();c.fillStyle=u.hp<=0?'#070b0c30':'#090c0d65';c.beginPath();c.ellipse(p.center,p.y+p.h-2,p.w*.32,3,0,0,Math.PI*2);c.fill();if(u.hp<=0)c.globalAlpha=.52;let shift=pose==='strike'&&!this.reduced?(side==='ally'?5:-5):pose==='anticipation'&&!this.reduced?(side==='ally'?-2:2):0;c.translate(p.center+shift,p.y);if(side==='enemy')c.scale(-1,1);if(pose==='hurt'&&!this.reduced&&Math.floor((time-a.start)/65)%2===0)c.globalAlpha=.5;c.drawImage(im,col*CELL.w,0,CELL.w,CELL.h,-p.w/2,0,p.w,p.h);c.restore();
 if(s.guard.has(u.id)){c.strokeStyle='#b9dcbb';c.lineWidth=1;c.strokeRect(p.center-p.w*.22,p.y+p.h*.36,p.w*.44,p.h*.45);}}
 for(const e of this.timeline.effects){const p=this.positions.get(e.id);if(!p)continue;const f=Math.min(3,Math.floor((time-e.start)/e.duration*4)),row=FX_NAMES.indexOf(e.kind),size=Math.min(108,p.h*1.12);c.save();c.beginPath();c.rect(0,p.rowY,this.width,p.rowH-25);c.clip();if(row>=0){c.globalAlpha=this.reduced?.65:1;c.drawImage(this.images.get(fxAtlas),f*128,row*128,128,128,p.center-size/2,p.y+p.h-size,size,size);if(['slash','thrust'].includes(e.kind)&&f===1)c.drawImage(this.images.get(fxAtlas),128,2*128,128,128,p.center-24,p.y+p.h*.3,48,48);}if(e.text){c.globalAlpha=1;c.font='bold 15px monospace';c.textAlign='center';c.lineWidth=3;c.strokeStyle='#09131f';c.fillStyle=e.kind==='heal'?'#c9ffca':'#fff1c6';const y=p.y+19-(this.reduced?0:Math.min(9,(time-e.start)/55));c.strokeText(e.text,p.center,y);c.fillText(e.text,p.center,y);}c.restore();}}
}
